# -*- coding: utf-8 -*-
"""Demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tOxOUSZ_D1_wDQuGftrDIxGddhwSK0Aq
"""

!pip -q install timm open_clip_torch faiss-cpu opencv-python-headless facenet-pytorch ultralytics pandas pillow matplotlib scikit-learn

from google.colab import drive
drive.mount("/content/drive")

import os, shutil

DRIVE_DIR = "/content/drive/MyDrive/PersonalFashionStylist"
LOCAL_DIR = "/content/stylist_demo_runtime"

os.makedirs(f"{LOCAL_DIR}/models", exist_ok=True)

# ---- copy models ----
for f in ["resnet18_best.pt", "effb0_best.pt"]:
    src = f"{DRIVE_DIR}/models/{f}"
    dst = f"{LOCAL_DIR}/models/{f}"
    assert os.path.exists(src), f"Missing in Drive: {src}"
    shutil.copy(src, dst)

# ---- copy index folder ----
src_index = f"{DRIVE_DIR}/clip_index/fashion_reco_index"
dst_index = f"{LOCAL_DIR}/fashion_reco_index"
assert os.path.exists(src_index), f"Missing in Drive: {src_index}"

if os.path.exists(dst_index):
    shutil.rmtree(dst_index)
shutil.copytree(src_index, dst_index)

print("Restored assets to:", LOCAL_DIR)
!ls -lh {LOCAL_DIR}/models
!ls -lh {LOCAL_DIR}/fashion_reco_index

import numpy as np, pandas as pd
import torch, torch.nn as nn
import torchvision.transforms as T
import torchvision.models as tvm
import timm
import faiss
import open_clip
from PIL import Image

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# Load index data
meta = pd.read_csv(f"{LOCAL_DIR}/fashion_reco_index/meta.csv")
emb_all = np.load(f"{LOCAL_DIR}/fashion_reco_index/clip_emb.npy")
index_all = faiss.read_index(f"{LOCAL_DIR}/fashion_reco_index/clip_faiss.index")

label_list = sorted(meta["label"].unique().tolist())
label2id = {l:i for i,l in enumerate(label_list)}
id2label = {i:l for l,i in label2id.items()}
num_classes = len(label_list)
print("Classes:", num_classes, label_list)

# Load classifiers
def load_ckpt(model, path):
    ck = torch.load(path, map_location="cpu")
    model.load_state_dict(ck["model"])
    return model.to(device).eval()

resnet = tvm.resnet18(weights=None)
resnet.fc = nn.Linear(resnet.fc.in_features, num_classes)
resnet = load_ckpt(resnet, f"{LOCAL_DIR}/models/resnet18_best.pt")

effnet = timm.create_model("efficientnet_b0", pretrained=False, num_classes=num_classes)
effnet = load_ckpt(effnet, f"{LOCAL_DIR}/models/effb0_best.pt")

eval_tf = T.Compose([
    T.Resize((224,224)),
    T.ToTensor(),
    T.Normalize((0.485,0.456,0.406),(0.229,0.224,0.225))
])

# Load CLIP
clip_model, _, clip_preprocess = open_clip.create_model_and_transforms(
    "ViT-B-32", pretrained="laion2b_s34b_b79k"
)
clip_model = clip_model.to(device).eval()
tokenizer = open_clip.get_tokenizer("ViT-B-32")

@torch.no_grad()
def clip_embed_one(img_path):
    x = clip_preprocess(Image.open(img_path).convert("RGB")).unsqueeze(0).to(device)
    f = clip_model.encode_image(x)
    f = f / f.norm(dim=-1, keepdim=True)
    return f.cpu().numpy().astype("float32")

@torch.no_grad()
def clip_text_embed_one(text):
    tokens = tokenizer([text]).to(device)
    t = clip_model.encode_text(tokens)
    t = t / t.norm(dim=-1, keepdim=True)
    return t.cpu().numpy().astype("float32")

@torch.no_grad()
def classify_both(img_path):
    x = eval_tf(Image.open(img_path).convert("RGB")).unsqueeze(0).to(device)
    lr = resnet(x)
    le = effnet(x)

    pr = torch.softmax(lr,1)[0].cpu().numpy()
    pe = torch.softmax(le,1)[0].cpu().numpy()
    pens = torch.softmax((lr+le)/2.0,1)[0].cpu().numpy()

    def pack(p):
        pred_id = int(p.argmax())
        return {"pred_id": pred_id, "pred_label": id2label[pred_id], "conf": float(p.max())}

    return pack(pr), pack(pe), pack(pens)

print("Loaded: ResNet18 + EfficientNet + CLIP + FAISS")

!pip -q install kagglehub
import kagglehub, os

dataset_id = "prashantsharma526/e-commerce-mens-clothing-dataset"
new_base = kagglehub.dataset_download(dataset_id)
new_data_root = os.path.join(new_base, "dataset_clean")

print("Downloaded dataset to:", new_base)
print("New data root:", new_data_root)

# Convert old absolute paths -> relative paths after 'dataset_clean/'
# then rebuild correct absolute paths for THIS runtime
meta["rel"] = meta["path"].astype(str).apply(lambda p: p.split("dataset_clean/")[-1])
meta["path"] = meta["rel"].apply(lambda r: os.path.join(new_data_root, r))
meta = meta.drop(columns=["rel"])

# sanity check
print("Example repaired path:", meta.iloc[0]["path"])
print("File exists?", os.path.exists(meta.iloc[0]["path"]))

import matplotlib.pyplot as plt
import faiss

TOP_CLASSES = {"casual_shirts", "formal_shirts", "printed_tshirts", "solid_tshirts", "printed_hoodies"}
BOTTOM_CLASSES = {"jeans", "formal_pants", "men_cargos"}

tops_meta_idx = meta.index[meta["label"].isin(TOP_CLASSES)].to_numpy()
bottoms_meta_idx = meta.index[meta["label"].isin(BOTTOM_CLASSES)].to_numpy()

emb_tops = emb_all[tops_meta_idx].astype("float32")
emb_bottoms = emb_all[bottoms_meta_idx].astype("float32")

D = emb_all.shape[1]
index_tops = faiss.IndexFlatIP(D); index_tops.add(emb_tops)
index_bottoms = faiss.IndexFlatIP(D); index_bottoms.add(emb_bottoms)

def show_outfit_2piece(left_img_path, recs_df, title="Recommendations"):
    k = len(recs_df)
    plt.figure(figsize=(3*(k+1), 5))

    plt.subplot(1, k+1, 1)
    plt.imshow(Image.open(left_img_path).convert("RGB"))
    plt.axis("off")
    plt.title("INPUT")

    for i, row in enumerate(recs_df.itertuples(), start=2):
        plt.subplot(1, k+1, i)
        plt.imshow(Image.open(row.path).convert("RGB"))
        plt.axis("off")
        # score column can be score/final_personal/etc.
        s = getattr(row, "score", None)
        if s is None and hasattr(row, "final_personal"):
            s = row.final_personal
        plt.title(f"{row.label}\n{s:.2f}" if s is not None else f"{row.label}")

    plt.suptitle(title)
    plt.tight_layout()
    plt.show()

print("Top index:", index_tops.ntotal, "Bottom index:", index_bottoms.ntotal)

import cv2, numpy as np

def clothing_color_stats(img_path, resize=180):
    img = np.array(Image.open(img_path).convert("RGB"))
    h, w = img.shape[:2]
    scale = resize / max(h, w)
    img = cv2.resize(img, (int(w*scale), int(h*scale)))

    hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)
    H, S, V = hsv[:,:,0], hsv[:,:,1], hsv[:,:,2]

    mask = (S > 35) & (V < 245)
    if mask.sum() < 200:
        mask = np.ones_like(S, dtype=bool)

    return float(H[mask].mean()), float(S[mask].mean()), float(V[mask].mean())

def hue_dist(h1, h2):
    d = abs(h1 - h2)
    return min(d, 180 - d)

def color_harmony_score(top_stats, bottom_stats):
    ht, st, vt = top_stats
    hb, sb, vb = bottom_stats

    neutral_bonus = 1.0 - min(sb/255.0, 1.0)
    if st > 90:  # colorful top => prefer neutral bottoms more
        neutral_bonus *= 1.3

    v_contrast = min(abs(vt - vb)/255.0, 1.0)
    hue_penalty = (hue_dist(ht, hb)/90.0) * (sb/255.0)

    return float(0.55*neutral_bonus + 0.35*v_contrast - 0.20*hue_penalty)

def color_family_from_hsv(h, s, v):
    if s < 45:
        return "neutral"
    if (h <= 35) or (h >= 160) or (35 < h <= 80):
        return "warm"
    return "cool"

def skin_match_score(item_hsv_stats, undertone):
    h, s, v = item_hsv_stats
    fam = color_family_from_hsv(h, s, v)
    if fam == "neutral":
        return 0.95
    if undertone == "neutral":
        return 0.80
    return 1.00 if fam == undertone else 0.45

def recommend_bottoms_free_text(top_img_path, occasion_text, k=5, search_k=120, w_img=0.70, w_txt=0.30):
    occasion_text = (occasion_text or "").strip() or "casual everyday"

    q_img = clip_embed_one(top_img_path)
    img_scores, idxs = index_bottoms.search(q_img, search_k)
    picked_meta_rows = bottoms_meta_idx[idxs[0]]

    cand = meta.iloc[picked_meta_rows].copy()
    cand["img_score"] = img_scores[0]

    templates = [
        f"men's {occasion_text} outfit pants",
        f"men's {occasion_text} trousers",
        f"men's {occasion_text} jeans outfit",
    ]
    t = np.mean([clip_text_embed_one(t) for t in templates], axis=0)
    t = t / np.linalg.norm(t, axis=1, keepdims=True)

    cand_emb = emb_all[picked_meta_rows]
    cand["txt_score"] = (cand_emb @ t.T).reshape(-1)

    cand["final_score"] = w_img*cand["img_score"] + w_txt*cand["txt_score"]
    cand = cand.sort_values("final_score", ascending=False).head(k).reset_index(drop=True)
    cand = cand.rename(columns={"final_score":"score"})
    return cand[["path","label","img_score","txt_score","score"]]

def recommend_tops_free_text(bottom_img_path, occasion_text, k=5, search_k=120, w_img=0.70, w_txt=0.30):
    occasion_text = (occasion_text or "").strip() or "casual everyday"

    q_img = clip_embed_one(bottom_img_path)
    img_scores, idxs = index_tops.search(q_img, search_k)
    picked_meta_rows = tops_meta_idx[idxs[0]]

    cand = meta.iloc[picked_meta_rows].copy()
    cand["img_score"] = img_scores[0]

    templates = [
        f"men's {occasion_text} shirt",
        f"men's {occasion_text} t-shirt",
        f"men's {occasion_text} hoodie",
    ]
    t = np.mean([clip_text_embed_one(t) for t in templates], axis=0)
    t = t / np.linalg.norm(t, axis=1, keepdims=True)

    cand_emb = emb_all[picked_meta_rows]
    cand["txt_score"] = (cand_emb @ t.T).reshape(-1)

    cand["final_score"] = w_img*cand["img_score"] + w_txt*cand["txt_score"]
    cand = cand.sort_values("final_score", ascending=False).head(k).reset_index(drop=True)
    cand = cand.rename(columns={"final_score":"score"})
    return cand[["path","label","img_score","txt_score","score"]]

def personalize_recs(query_top_path, cand_df, skin_profile, is_top_query=True):
    undertone = (skin_profile or {}).get("undertone", "neutral")

    if is_top_query:
        top_hsv = clothing_color_stats(query_top_path)
        cand_df = cand_df.copy()
        cand_df["item_hsv"] = cand_df["path"].apply(clothing_color_stats)
        cand_df["harmony"] = cand_df["item_hsv"].apply(lambda b: color_harmony_score(top_hsv, b))
    else:
        bottom_hsv = clothing_color_stats(query_top_path)
        cand_df = cand_df.copy()
        cand_df["item_hsv"] = cand_df["path"].apply(clothing_color_stats)
        cand_df["harmony"] = cand_df["item_hsv"].apply(lambda top_hsv: color_harmony_score(top_hsv, bottom_hsv))

    cand_df["skin"] = cand_df["item_hsv"].apply(lambda st: skin_match_score(st, undertone))
    cand_df["score2"] = 0.65*cand_df["score"] + 0.20*cand_df["harmony"] + 0.15*cand_df["skin"]
    cand_df = cand_df.sort_values("score2", ascending=False).reset_index(drop=True)
    cand_df = cand_df.rename(columns={"score2":"score"})
    return cand_df[["path","label","img_score","txt_score","harmony","skin","score"]]

CLOTHING_PROMPTS = [
    "a photo of clothing",
    "a photo of a shirt",
    "a photo of pants",
    "a fashion product photo",
]
NONCLOTHING_PROMPTS = [
    "a photo of a car",
    "a photo of a dog",
    "a photo of food",
    "a photo of a building",
    "a random object photo",
]

def _mean_text_vec(prompts):
    vecs = np.vstack([clip_text_embed_one(p) for p in prompts])
    v = vecs.mean(axis=0, keepdims=True)
    v = v / np.linalg.norm(v, axis=1, keepdims=True)
    return v.astype("float32")

cloth_vec = _mean_text_vec(CLOTHING_PROMPTS)
non_vec   = _mean_text_vec(NONCLOTHING_PROMPTS)

def is_clothing_image(img_path, margin=0.03):
    v = clip_embed_one(img_path)
    clothing_score = float(v @ cloth_vec.T)
    non_score = float(v @ non_vec.T)
    ok = clothing_score > (non_score + margin)
    return ok, clothing_score, non_score

def safe_demo_item(img_path, occasion_text="casual everyday", skin_profile=None,
                   classifier_choice="ensemble", min_class_conf=0.70, k=5):
    ok, cs, ns = is_clothing_image(img_path)
    if not ok:
        print("Rejected: does not look like clothing/person.")
        print(f"CLIP clothing_score={cs:.3f} nonclothing_score={ns:.3f}")
        return

    r, e, ens = classify_both(img_path)
    chosen = {"resnet": r, "effnet": e, "ensemble": ens}[classifier_choice]

    print("ResNet18 :", r)
    print("EffNet   :", e)
    print("Ensemble :", ens)
    print("Chosen   :", chosen)

    if chosen["conf"] < min_class_conf:
        print("Low confidence. Please upload a clearer clothing image.")
        return

    pred_label = chosen["pred_label"]

    if pred_label in TOP_CLASSES:
        recs = recommend_bottoms_free_text(img_path, occasion_text, k=k, search_k=150)
        recs = personalize_recs(img_path, recs, skin_profile, is_top_query=True)
        show_outfit_2piece(img_path, recs, title=f"TOP → Bottoms | occasion='{occasion_text}'")

    elif pred_label in BOTTOM_CLASSES:
        recs = recommend_tops_free_text(img_path, occasion_text, k=k, search_k=150)
        recs = personalize_recs(img_path, recs, skin_profile, is_top_query=False)
        show_outfit_2piece(img_path, recs, title=f"BOTTOM → Tops | occasion='{occasion_text}'")

    else:
        print("Predicted class not mapped to TOP/BOTTOM. (This dataset has no shoes.)")

import cv2, numpy as np
from facenet_pytorch import MTCNN

mtcnn = MTCNN(keep_all=True, device=device)

def clamp(v, lo, hi):
    return max(lo, min(hi, v))

def skin_mask_ycrcb(roi_bgr):
    ycrcb = cv2.cvtColor(roi_bgr, cv2.COLOR_BGR2YCrCb)
    Y, Cr, Cb = cv2.split(ycrcb)
    mask = (Cr >= 133) & (Cr <= 173) & (Cb >= 77) & (Cb <= 127)
    mask = mask & (Y > 30) & (Y < 245)
    return mask

def face_and_cheeks_bboxes(img_bgr, face_xyxy):
    h, w = img_bgr.shape[:2]
    x1, y1, x2, y2 = [int(v) for v in face_xyxy]
    x1 = clamp(x1, 0, w-2); y1 = clamp(y1, 0, h-2)
    x2 = clamp(x2, x1+2, w); y2 = clamp(y2, y1+2, h)

    bw, bh = x2-x1, y2-y1
    face = (x1, y1, bw, bh)

    cy1 = y1 + int(0.45 * bh)
    cy2 = y1 + int(0.70 * bh)

    lx1 = x1 + int(0.15 * bw); lx2 = x1 + int(0.40 * bw)
    rx1 = x1 + int(0.60 * bw); rx2 = x1 + int(0.85 * bw)

    left  = (lx1, cy1, max(2, lx2-lx1), max(2, cy2-cy1))
    right = (rx1, cy1, max(2, rx2-rx1), max(2, cy2-cy1))
    return face, left, right

def crop_xywh(img_bgr, bb):
    x,y,w,h = bb
    return img_bgr[y:y+h, x:x+w].copy()

def estimate_skin_profile_detailed(face_img_path, show=True):
    img_rgb = np.array(Image.open(face_img_path).convert("RGB"))
    img_bgr = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2BGR)

    boxes, probs, landmarks = mtcnn.detect(Image.fromarray(img_rgb), landmarks=True)
    if boxes is None or len(boxes) == 0:
        raise ValueError("No face detected. Upload a clearer front-facing photo.")

    best_i = int(np.argmax(probs))
    face_xyxy = boxes[best_i]
    face_bb, left_bb, right_bb = face_and_cheeks_bboxes(img_bgr, face_xyxy)

    pixels = []
    for bb in [left_bb, right_bb]:
        roi = crop_xywh(img_bgr, bb)
        if roi.size == 0:
            continue
        mask = skin_mask_ycrcb(roi)
        if mask.sum() < 80:
            mask = np.ones(mask.shape, dtype=bool)
        pixels.append(roi[mask])

    pixels = np.vstack(pixels).astype(np.uint8)

    lab = cv2.cvtColor(pixels.reshape(-1,1,3), cv2.COLOR_BGR2LAB).reshape(-1,3)
    L_mean, a_mean, b_mean = lab.mean(axis=0)
    delta_b = b_mean - 128

    if delta_b > 6:
        undertone = "warm"
    elif delta_b < -6:
        undertone = "cool"
    else:
        undertone = "neutral"

    if L_mean >= 190: tone_detail = "very light"
    elif L_mean >= 170: tone_detail = "light"
    elif L_mean >= 135: tone_detail = "medium"
    elif L_mean >= 110: tone_detail = "tan"
    else: tone_detail = "deep"

    profile = {
        "tone_detail": tone_detail,
        "undertone": undertone,
        "L_mean": float(L_mean),
        "b_minus_128": float(delta_b),
    }

    if show:
        vis = img_rgb.copy()
        for (x,y,w,h), color, name in [
            (face_bb, (0,255,0), "face"),
            (left_bb, (255,0,0), "L cheek"),
            (right_bb, (0,0,255), "R cheek")
        ]:
            cv2.rectangle(vis, (x,y), (x+w,y+h), color, 2)
            cv2.putText(vis, name, (x, max(0,y-8)), cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)

        plt.figure(figsize=(6,6))
        plt.imshow(vis); plt.axis("off")
        plt.title(f"tone={tone_detail}, undertone={undertone} | b-128={delta_b:.1f}")
        plt.show()

    return profile

import cv2, numpy as np
from ultralytics import YOLO

pose_model = YOLO("yolov8s-pose.pt")

def crop_top_bottom_from_person(person_path):
    img_bgr = cv2.imread(person_path)
    if img_bgr is None:
        raise ValueError("Could not read image.")
    H, W = img_bgr.shape[:2]

    res = pose_model.predict(person_path, conf=0.25, verbose=False)[0]
    if res.keypoints is None or len(res.keypoints) == 0:
        raise ValueError("No person detected. Upload a clearer full-body standing photo.")

    best_i = int(np.argmax(res.boxes.conf.cpu().numpy()))
    kpts = res.keypoints.xy[best_i].cpu().numpy()
    x1, y1, x2, y2 = res.boxes.xyxy[best_i].cpu().numpy()
    x1, y1, x2, y2 = map(int, [x1,y1,x2,y2])

    # COCO indices
    L_SH, R_SH = 5, 6
    L_HIP, R_HIP = 11, 12
    L_ANK, R_ANK = 15, 16

    def clampi(v, lo, hi): return int(max(lo, min(hi, v)))
    def safe_xy(points):
        pts = points.copy()
        good = ~np.isnan(pts[:,0]) & ~np.isnan(pts[:,1]) & (pts[:,0] > 1) & (pts[:,1] > 1)
        return pts[good] if good.any() else pts

    shoulders = safe_xy(kpts[[L_SH, R_SH]])
    hips      = safe_xy(kpts[[L_HIP, R_HIP]])
    ankles    = safe_xy(kpts[[L_ANK, R_ANK]])

    if shoulders.size and hips.size:
        top_y1 = min(shoulders[:,1].min(), hips[:,1].min())
        top_y2 = hips[:,1].max()
        top_x1 = min(shoulders[:,0].min(), hips[:,0].min())
        top_x2 = max(shoulders[:,0].max(), hips[:,0].max())
    else:
        top_x1, top_y1, top_x2, top_y2 = x1, y1, x2, int((y1+y2)/2)

    if hips.size and ankles.size:
        bot_y1 = hips[:,1].min()
        bot_y2 = ankles[:,1].max()
        bot_x1 = min(hips[:,0].min(), ankles[:,0].min())
        bot_x2 = max(hips[:,0].max(), ankles[:,0].max())
    else:
        bot_x1, bot_y1, bot_x2, bot_y2 = x1, int((y1+y2)/2), x2, y2

    pad_x = int(0.10 * (x2-x1))
    pad_y = int(0.08 * (y2-y1))

    top_x1 = clampi(top_x1-pad_x, 0, W-1); top_x2 = clampi(top_x2+pad_x, 0, W-1)
    top_y1 = clampi(top_y1-pad_y, 0, H-1); top_y2 = clampi(top_y2+pad_y, 0, H-1)

    bot_x1 = clampi(bot_x1-pad_x, 0, W-1); bot_x2 = clampi(bot_x2+pad_x, 0, W-1)
    bot_y1 = clampi(bot_y1-pad_y, 0, H-1); bot_y2 = clampi(bot_y2+pad_y, 0, H-1)

    top_crop = img_bgr[top_y1:top_y2, top_x1:top_x2].copy()
    bot_crop = img_bgr[bot_y1:bot_y2, bot_x1:bot_x2].copy()

    top_path = "/content/top_crop.jpg"
    bot_path = "/content/bottom_crop.jpg"
    cv2.imwrite(top_path, top_crop)
    cv2.imwrite(bot_path, bot_crop)

    return top_path, bot_path

def style_from_person_photo(person_path, occasion_text="casual everyday", skin_profile=None, k=5):
    top_path, bot_path = crop_top_bottom_from_person(person_path)

    print("Crops created:", top_path, bot_path)
    show_outfit_2piece(person_path, pd.DataFrame([{"path": top_path, "label":"TOP_CROP", "score":1.0},
                                                  {"path": bot_path, "label":"BOTTOM_CROP", "score":1.0}]),
                       title="Person photo + crops")

    print("\n--- TOP crop → bottoms ---")
    safe_demo_item(top_path, occasion_text=occasion_text, skin_profile=skin_profile, classifier_choice="ensemble", k=k)

    print("\n--- BOTTOM crop → tops ---")
    safe_demo_item(bot_path, occasion_text=occasion_text, skin_profile=skin_profile, classifier_choice="ensemble", k=k)

from google.colab import files
uploaded = files.upload()
img_path = "/content/" + list(uploaded.keys())[0]

# (optional) set skin_profile=None if you don't want skin personalization
skin_profile = {"undertone": "neutral"}

safe_demo_item(img_path, occasion_text="office meeting", skin_profile=skin_profile, k=5)

uploaded = files.upload()
face_path = "/content/" + list(uploaded.keys())[0]

skin_profile = estimate_skin_profile_detailed(face_path, show=True)
print("Skin profile:", skin_profile)

uploaded = files.upload()
person_path = "/content/" + list(uploaded.keys())[0]

# use skin_profile from CELL 10 if you computed it; otherwise set neutral:
# skin_profile = {"undertone": "neutral"}

style_from_person_photo(person_path, occasion_text="wedding guest", skin_profile=skin_profile, k=5)

import pandas as pd, os
meta = pd.read_csv("/content/stylist_demo_runtime/fashion_reco_index/meta.csv")
print(meta.iloc[0]["path"])
print("exists?", os.path.exists(meta.iloc[0]["path"]))

!find /content -maxdepth 3 -type f -name "*best.pt" -print
!find /content/stylist_demo_runtime -maxdepth 3 -type f -name "*.pt" -print

!pip -q install seaborn matplotlib scikit-learn pandas

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import torch.nn as nn
import torch.nn.functional as F

from sklearn.metrics import (
    confusion_matrix, classification_report,
    accuracy_score, f1_score, precision_score, recall_score,
    roc_curve, auc
)
from sklearn.preprocessing import label_binarize

# --- SimpleCNN (same as training) ---
class SimpleCNN(nn.Module):
    def __init__(self, num_classes=8):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 32, 3, padding=1), nn.BatchNorm2d(32), nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(32, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(64, 128, 3, padding=1), nn.BatchNorm2d(128), nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(128, 256, 3, padding=1), nn.BatchNorm2d(256), nn.ReLU(),
            nn.AdaptiveAvgPool2d((1,1))
        )
        self.classifier = nn.Sequential(nn.Dropout(0.3), nn.Linear(256, num_classes))

    def forward(self, x):
        x = self.features(x).flatten(1)
        return self.classifier(x)

def load_ckpt(model, ckpt_path):
    ck = torch.load(ckpt_path, map_location="cpu")
    model.load_state_dict(ck["model"])
    return model.to(device).eval()

num_classes = len(label_list)

# CNN
cnn = SimpleCNN(num_classes=num_classes)
cnn = load_ckpt(cnn, "/content/drive/MyDrive/PersonalFashionStylist/models/cnn_best.pt")

# ResNet18
import torchvision.models as tvm
resnet = tvm.resnet18(weights=None)
resnet.fc = nn.Linear(resnet.fc.in_features, num_classes)
resnet = load_ckpt(resnet, "/content/drive/MyDrive/PersonalFashionStylist/models/resnet18_best.pt")

# EfficientNet-B0
import timm
eff = timm.create_model("efficientnet_b0", pretrained=False, num_classes=num_classes)
eff = load_ckpt(eff, "/content/drive/MyDrive/PersonalFashionStylist/models/effb0_best.pt")

print("Loaded all 3 models.")

!pip -q install kagglehub

import kagglehub, os
from pathlib import Path
import pandas as pd

base = kagglehub.dataset_download("prashantsharma526/e-commerce-mens-clothing-dataset")
DATA_ROOT = Path(base) / "dataset_clean"
print("DATA_ROOT:", DATA_ROOT)

IMG_EXTS = {".jpg",".jpeg",".png",".webp"}

rows = []
for cls_dir in sorted(DATA_ROOT.iterdir()):
    if not cls_dir.is_dir():
        continue
    label = cls_dir.name
    # sort to make ordering deterministic
    files = sorted([p for p in cls_dir.rglob("*") if p.suffix.lower() in IMG_EXTS])
    for p in files:
        rows.append({"path": str(p), "label": label})

df = pd.DataFrame(rows)
print("Images:", len(df), "Classes:", df["label"].nunique())
df["label"].value_counts()

import torch
from sklearn.model_selection import train_test_split
from PIL import Image
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as T

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# label mapping (must match training: sorted unique labels)
label_list = sorted(df["label"].unique().tolist())
label2id = {l:i for i,l in enumerate(label_list)}
id2label = {i:l for l,i in label2id.items()}
df["y"] = df["label"].map(label2id)

train_df, temp_df = train_test_split(df, test_size=0.30, random_state=42, stratify=df["y"])
val_df, test_df   = train_test_split(temp_df, test_size=0.50, random_state=42, stratify=temp_df["y"])

print("Train:", len(train_df), "Val:", len(val_df), "Test:", len(test_df))

IMG_SIZE = 224
eval_tf = T.Compose([
    T.Resize((IMG_SIZE, IMG_SIZE)),
    T.ToTensor(),
    T.Normalize((0.485,0.456,0.406),(0.229,0.224,0.225))
])

class ClothesDataset(Dataset):
    def __init__(self, df, transform):
        self.df = df.reset_index(drop=True)
        self.transform = transform
    def __len__(self): return len(self.df)
    def __getitem__(self, idx):
        p = self.df.loc[idx, "path"]
        y = int(self.df.loc[idx, "y"])
        img = Image.open(p).convert("RGB")
        return self.transform(img), y

test_loader = DataLoader(
    ClothesDataset(test_df, eval_tf),
    batch_size=32, shuffle=False,
    num_workers=2,
    pin_memory=(device=="cuda")
)

# sanity check
xb, yb = next(iter(test_loader))
print("Batch:", xb.shape, yb.shape)

y_true, y_pred, y_prob = collect_outputs(model, test_loader)

@torch.no_grad()
def collect_outputs(model, loader):
    model.eval()
    ys, preds, probs = [], [], []
    for x, y in loader:
        x = x.to(device)
        logits = model(x)
        p = torch.softmax(logits, dim=1).cpu().numpy()  # (B,C)
        pred = p.argmax(axis=1)

        ys.append(y.numpy())
        preds.append(pred)
        probs.append(p)

    y_true = np.concatenate(ys)
    y_pred = np.concatenate(preds)
    y_prob = np.vstack(probs)
    return y_true, y_pred, y_prob

def plot_confusion(y_true, y_pred, labels, title, normalize=False, save_path=None):
    cm = confusion_matrix(y_true, y_pred)
    if normalize:
        cm = cm.astype(float) / cm.sum(axis=1, keepdims=True)

    plt.figure(figsize=(9,7))
    sns.heatmap(
        cm, cmap="Blues",
        xticklabels=labels, yticklabels=labels,
        annot=False, fmt=".2f" if normalize else "d"
    )
    plt.title(title + (" (Normalized)" if normalize else ""))
    plt.xlabel("Predicted"); plt.ylabel("True")
    plt.tight_layout()
    if save_path: plt.savefig(save_path, dpi=200)
    plt.show()

def plot_per_class_f1(y_true, y_pred, labels, title, save_path=None):
    f1s = f1_score(y_true, y_pred, average=None)
    dfm = pd.DataFrame({"class": labels, "F1": f1s}).sort_values("F1", ascending=False)

    plt.figure(figsize=(10,4))
    sns.barplot(data=dfm, x="class", y="F1", color="#4f46e5")
    plt.xticks(rotation=35, ha="right")
    plt.ylim(0, 1)
    plt.title(title + " — Per-class F1")
    plt.tight_layout()
    if save_path: plt.savefig(save_path, dpi=200)
    plt.show()

def plot_prf_heatmap(y_true, y_pred, labels, title, save_path=None):
    p = precision_score(y_true, y_pred, average=None, zero_division=0)
    r = recall_score(y_true, y_pred, average=None, zero_division=0)
    f = f1_score(y_true, y_pred, average=None, zero_division=0)

    mat = pd.DataFrame({"precision": p, "recall": r, "f1": f}, index=labels)
    plt.figure(figsize=(6, len(labels)*0.45 + 1))
    sns.heatmap(mat, annot=True, cmap="YlGnBu", fmt=".2f")
    plt.title(title + " — Precision/Recall/F1 by class")
    plt.tight_layout()
    if save_path: plt.savefig(save_path, dpi=200)
    plt.show()

def plot_confidence_hist(y_true, y_pred, y_prob, title, save_path=None):
    conf = y_prob.max(axis=1)
    correct = (y_true == y_pred)

    plt.figure(figsize=(8,4))
    sns.histplot(conf[correct], color="green", bins=20, stat="density", label="Correct", alpha=0.55)
    sns.histplot(conf[~correct], color="red", bins=20, stat="density", label="Wrong", alpha=0.55)
    plt.title(title + " — Confidence distribution")
    plt.xlabel("Max softmax probability")
    plt.legend()
    plt.tight_layout()
    if save_path: plt.savefig(save_path, dpi=200)
    plt.show()

def plot_reliability_curve(y_true, y_prob, title, n_bins=10, save_path=None):
    conf = y_prob.max(axis=1)
    pred = y_prob.argmax(axis=1)
    correct = (pred == y_true).astype(float)

    bins = np.linspace(0, 1, n_bins+1)
    bin_ids = np.digitize(conf, bins) - 1

    accs, confs = [], []
    for b in range(n_bins):
        m = bin_ids == b
        if m.sum() == 0:
            continue
        accs.append(correct[m].mean())
        confs.append(conf[m].mean())

    plt.figure(figsize=(5,5))
    plt.plot([0,1],[0,1],"k--",label="Perfect calibration")
    plt.plot(confs, accs, marker="o", label="Model")
    plt.title(title + " — Reliability curve")
    plt.xlabel("Avg confidence")
    plt.ylabel("Accuracy in bin")
    plt.legend()
    plt.tight_layout()
    if save_path: plt.savefig(save_path, dpi=200)
    plt.show()

def plot_multiclass_roc(y_true, y_prob, labels, title, save_path=None):
    Y = label_binarize(y_true, classes=np.arange(len(labels)))

    plt.figure(figsize=(7,6))
    for i, cls in enumerate(labels):
        fpr, tpr, _ = roc_curve(Y[:, i], y_prob[:, i])
        roc_auc = auc(fpr, tpr)
        plt.plot(fpr, tpr, linewidth=1.2, label=f"{cls} (AUC={roc_auc:.2f})")

    plt.plot([0,1],[0,1],"k--",linewidth=1)
    plt.title(title + " — ROC (OvR)")
    plt.xlabel("FPR"); plt.ylabel("TPR")
    plt.legend(fontsize=8, bbox_to_anchor=(1.02, 1), loc="upper left")
    plt.tight_layout()
    if save_path: plt.savefig(save_path, dpi=200)
    plt.show()

import os
OUT = "/content/model_graphs"
os.makedirs(OUT, exist_ok=True)

models = {
    "SimpleCNN": cnn,
    "ResNet18": resnet,
    "EfficientNet-B0": eff
}

summary = []
for name, model in models.items():
    y_true, y_pred, y_prob = collect_outputs(model, test_loader)

    acc = accuracy_score(y_true, y_pred)
    mf1 = f1_score(y_true, y_pred, average="macro")
    summary.append({"Model": name, "Test Accuracy": acc, "Test Macro-F1": mf1})

    print("\n==========", name, "==========")
    print(f"Test Accuracy: {acc:.4f} | Test Macro-F1: {mf1:.4f}")
    print(classification_report(y_true, y_pred, target_names=label_list, digits=4))

    plot_confusion(y_true, y_pred, label_list, f"{name} Confusion Matrix",
                   normalize=False, save_path=f"{OUT}/{name}_cm_raw.png")
    plot_confusion(y_true, y_pred, label_list, f"{name} Confusion Matrix",
                   normalize=True, save_path=f"{OUT}/{name}_cm_norm.png")

    plot_per_class_f1(y_true, y_pred, label_list, name,
                      save_path=f"{OUT}/{name}_perclass_f1.png")

    plot_prf_heatmap(y_true, y_pred, label_list, name,
                     save_path=f"{OUT}/{name}_prf_heatmap.png")

    plot_confidence_hist(y_true, y_pred, y_prob, name,
                         save_path=f"{OUT}/{name}_confidence_hist.png")

    plot_reliability_curve(y_true, y_prob, name,
                           save_path=f"{OUT}/{name}_reliability.png")

    # optional (comment out if too busy)
    # plot_multiclass_roc(y_true, y_prob, label_list, name,
    #                     save_path=f"{OUT}/{name}_roc.png")

pd.DataFrame(summary).sort_values("Test Macro-F1", ascending=False)

!ls -lh /content/model_graphs

import os, shutil

SRC = "/content/model_graphs"
DST = "/content/drive/MyDrive/PersonalFashionStylist/graphs"

assert os.path.exists(SRC), f"Missing folder: {SRC}"
os.makedirs(DST, exist_ok=True)

# overwrite old graphs folder
if os.path.exists(DST):
    shutil.rmtree(DST)
shutil.copytree(SRC, DST)

print("Saved graphs to:", DST)
!ls -lh "{DST}"