# -*- coding: utf-8 -*-
"""INT482_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZPSxrbJ4XHdYgTPhH9hnGH1iJUu2zkCM
"""

!pip -q install kagglehub timm open_clip_torch faiss-cpu scikit-learn seaborn pandas tqdm pillow matplotlib

import kagglehub, os
path = kagglehub.dataset_download("prashantsharma526/e-commerce-mens-clothing-dataset")
print("Path to dataset files:", path)

# Quick peek
!find "{path}" -maxdepth 3 -type d
!find "{path}" -maxdepth 3 -type f | head -n 30

!pip -q install pandas scikit-learn pillow

from pathlib import Path
import pandas as pd

BASE = Path("/root/.cache/kagglehub/datasets/prashantsharma526/e-commerce-mens-clothing-dataset/versions/2")
DATA_ROOT = BASE / "dataset_clean"

IMG_EXTS = {".jpg", ".jpeg", ".png", ".webp"}

rows = []
for cls_dir in sorted(DATA_ROOT.iterdir()):
    if not cls_dir.is_dir():
        continue
    label = cls_dir.name
    for p in cls_dir.rglob("*"):
        if p.suffix.lower() in IMG_EXTS:
            rows.append({"path": str(p), "label": label})

df = pd.DataFrame(rows)
print("Total images:", len(df))
print("Classes:", df["label"].nunique())
df["label"].value_counts()

label_list = sorted(df["label"].unique().tolist())
label2id = {l:i for i,l in enumerate(label_list)}
id2label = {i:l for l,i in label2id.items()}

df["y"] = df["label"].map(label2id)

label_list, df.head(3)

from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(
    df, test_size=0.30, random_state=42, stratify=df["y"]
)
val_df, test_df = train_test_split(
    temp_df, test_size=0.50, random_state=42, stratify=temp_df["y"]
)

print("Train:", len(train_df), "Val:", len(val_df), "Test:", len(test_df))
print("Train class counts:\n", train_df["label"].value_counts())

from PIL import Image
import matplotlib.pyplot as plt

p = train_df.iloc[0]["path"]
lab = train_df.iloc[0]["label"]
img = Image.open(p).convert("RGB")

plt.figure(figsize=(4,4))
plt.imshow(img)
plt.title(lab)
plt.axis("off")
plt.show()

!pip -q install torchvision

import torch
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as T
from PIL import Image

device = "cuda" if torch.cuda.is_available() else "cpu"
device

IMG_SIZE = 224

train_tf = T.Compose([
    T.Resize((IMG_SIZE, IMG_SIZE)),
    T.RandomHorizontalFlip(p=0.5),
    T.ColorJitter(brightness=0.15, contrast=0.15, saturation=0.10, hue=0.02),
    T.ToTensor(),
    T.Normalize(mean=(0.485, 0.456, 0.406),
                std=(0.229, 0.224, 0.225)),
])

eval_tf = T.Compose([
    T.Resize((IMG_SIZE, IMG_SIZE)),
    T.ToTensor(),
    T.Normalize(mean=(0.485, 0.456, 0.406),
                std=(0.229, 0.224, 0.225)),
])

IMG_SIZE = 224

train_tf = T.Compose([
    T.Resize((IMG_SIZE, IMG_SIZE)),
    T.RandomHorizontalFlip(p=0.5),
    T.ColorJitter(brightness=0.15, contrast=0.15, saturation=0.10, hue=0.02),
    T.ToTensor(),
    T.Normalize(mean=(0.485, 0.456, 0.406),
                std=(0.229, 0.224, 0.225)),
])

eval_tf = T.Compose([
    T.Resize((IMG_SIZE, IMG_SIZE)),
    T.ToTensor(),
    T.Normalize(mean=(0.485, 0.456, 0.406),
                std=(0.229, 0.224, 0.225)),
])

class ClothesDataset(Dataset):
    def __init__(self, df, transform):
        self.df = df.reset_index(drop=True)
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        path = self.df.loc[idx, "path"]
        y = int(self.df.loc[idx, "y"])
        img = Image.open(path).convert("RGB")
        img = self.transform(img)
        return img, y

BATCH_SIZE = 32

train_loader = DataLoader(
    ClothesDataset(train_df, train_tf),
    batch_size=BATCH_SIZE, shuffle=True,
    num_workers=2, pin_memory=True
)

val_loader = DataLoader(
    ClothesDataset(val_df, eval_tf),
    batch_size=BATCH_SIZE, shuffle=False,
    num_workers=2, pin_memory=True
)

test_loader = DataLoader(
    ClothesDataset(test_df, eval_tf),
    batch_size=BATCH_SIZE, shuffle=False,
    num_workers=2, pin_memory=True
)

xb, yb = next(iter(train_loader))
xb.shape, yb[:10]

import matplotlib.pyplot as plt
import numpy as np

def denorm(x):
    mean = np.array([0.485,0.456,0.406])
    std  = np.array([0.229,0.224,0.225])
    x = x.transpose(1,2,0)
    x = std*x + mean
    return np.clip(x, 0, 1)

plt.figure(figsize=(12,6))
for i in range(8):
    img, y = train_loader.dataset[i]
    plt.subplot(2,4,i+1)
    plt.imshow(denorm(img.numpy()))
    plt.title(id2label[int(y)])
    plt.axis("off")
plt.tight_layout()
plt.show()

!pip -q install scikit-learn tqdm

import torch.nn as nn
from sklearn.metrics import accuracy_score, f1_score
from tqdm import tqdm

@torch.no_grad()
def evaluate(model, loader):
    model.eval()
    ce = nn.CrossEntropyLoss()
    total_loss = 0.0
    ys, ps = [], []
    for x, y in loader:
        x, y = x.to(device), y.to(device)
        logits = model(x)
        loss = ce(logits, y)
        total_loss += loss.item() * x.size(0)
        pred = logits.argmax(1)
        ys.append(y.cpu()); ps.append(pred.cpu())
    ys = torch.cat(ys).numpy()
    ps = torch.cat(ps).numpy()
    return (total_loss / len(loader.dataset),
            accuracy_score(ys, ps),
            f1_score(ys, ps, average="macro"))

def train_model(model, train_loader, val_loader, epochs=5, lr=3e-4, save_path="/content/resnet18_best.pt"):
    model.to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
    scaler = torch.cuda.amp.GradScaler(enabled=(device=="cuda"))
    ce = nn.CrossEntropyLoss()

    best_mf1 = -1.0

    for ep in range(1, epochs+1):
        model.train()
        running = 0.0

        for x, y in tqdm(train_loader, desc=f"Epoch {ep}/{epochs}"):
            x, y = x.to(device), y.to(device)
            opt.zero_grad(set_to_none=True)

            with torch.cuda.amp.autocast(enabled=(device=="cuda")):
                logits = model(x)
                loss = ce(logits, y)

            scaler.scale(loss).backward()
            scaler.step(opt)
            scaler.update()

            running += loss.item() * x.size(0)

        train_loss = running / len(train_loader.dataset)
        val_loss, val_acc, val_mf1 = evaluate(model, val_loader)
        print(f"Epoch {ep}: train_loss={train_loss:.4f} | val_loss={val_loss:.4f} | val_acc={val_acc:.4f} | val_macroF1={val_mf1:.4f}")

        if val_mf1 > best_mf1:
            best_mf1 = val_mf1
            torch.save({"model": model.state_dict()}, save_path)
            print("  saved best ->", save_path)

    print("Best val macro-F1:", best_mf1)
    return best_mf1

import torchvision.models as tvm

num_classes = len(label_list)

resnet18 = tvm.resnet18(weights=tvm.ResNet18_Weights.IMAGENET1K_V1)
resnet18.fc = nn.Linear(resnet18.fc.in_features, num_classes)

resnet18

best_mf1 = train_model(
    resnet18,
    train_loader,
    val_loader,
    epochs=5,
    lr=3e-4,
    save_path="/content/resnet18_best.pt"
)

import numpy as np

def load_best(model, ckpt_path):
    ck = torch.load(ckpt_path, map_location="cpu")
    model.load_state_dict(ck["model"])
    return model.to(device).eval()

@torch.no_grad()
def predict_all(model, loader):
    ys, ps = [], []
    for x, y in loader:
        x = x.to(device)
        pred = model(x).argmax(1).cpu().numpy()
        ys.append(y.numpy()); ps.append(pred)
    return np.concatenate(ys), np.concatenate(ps)

resnet18_test = tvm.resnet18(weights=None)
resnet18_test.fc = nn.Linear(resnet18_test.fc.in_features, num_classes)
resnet18_test = load_best(resnet18_test, "/content/resnet18_best.pt")

y_true, y_pred = predict_all(resnet18_test, test_loader)

print("TEST Accuracy:", accuracy_score(y_true, y_pred))
print("TEST Macro-F1:", f1_score(y_true, y_pred, average="macro"))

!pip -q install timm

import torch
import torch.nn as nn
from tqdm import tqdm
from sklearn.metrics import accuracy_score, f1_score

amp_device = "cuda" if torch.cuda.is_available() else "cpu"

@torch.no_grad()
def evaluate(model, loader):
    model.eval()
    ce = nn.CrossEntropyLoss()
    total_loss = 0.0
    ys, ps = [], []
    for x, y in loader:
        x, y = x.to(device), y.to(device)
        logits = model(x)
        loss = ce(logits, y)
        total_loss += loss.item() * x.size(0)
        pred = logits.argmax(1)
        ys.append(y.cpu()); ps.append(pred.cpu())
    ys = torch.cat(ys).numpy()
    ps = torch.cat(ps).numpy()
    return (total_loss / len(loader.dataset),
            accuracy_score(ys, ps),
            f1_score(ys, ps, average="macro"))

def train_model_amp(model, train_loader, val_loader, epochs=5, lr=3e-4, save_path="/content/effb0_best.pt"):
    model.to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
    scaler = torch.amp.GradScaler(amp_device, enabled=(amp_device == "cuda"))
    ce = nn.CrossEntropyLoss()

    best_mf1 = -1.0

    for ep in range(1, epochs+1):
        model.train()
        running = 0.0

        for x, y in tqdm(train_loader, desc=f"Epoch {ep}/{epochs}"):
            x, y = x.to(device), y.to(device)
            opt.zero_grad(set_to_none=True)

            with torch.amp.autocast(device_type=amp_device, enabled=(amp_device == "cuda")):
                logits = model(x)
                loss = ce(logits, y)

            scaler.scale(loss).backward()
            scaler.step(opt)
            scaler.update()

            running += loss.item() * x.size(0)

        train_loss = running / len(train_loader.dataset)
        val_loss, val_acc, val_mf1 = evaluate(model, val_loader)
        print(f"Epoch {ep}: train_loss={train_loss:.4f} | val_loss={val_loss:.4f} | val_acc={val_acc:.4f} | val_macroF1={val_mf1:.4f}")

        if val_mf1 > best_mf1:
            best_mf1 = val_mf1
            torch.save({"model": model.state_dict()}, save_path)
            print("  saved best ->", save_path)

    print("Best val macro-F1:", best_mf1)
    return best_mf1

import timm
import torch.nn as nn

num_classes = len(label_list)

effb0 = timm.create_model("efficientnet_b0", pretrained=True, num_classes=num_classes)
effb0

eff_best = train_model_amp(
    effb0,
    train_loader,
    val_loader,
    epochs=5,
    lr=3e-4,
    save_path="/content/effb0_best.pt"
)

import numpy as np
from sklearn.metrics import accuracy_score, f1_score

def load_best(model, ckpt_path):
    ck = torch.load(ckpt_path, map_location="cpu")
    model.load_state_dict(ck["model"])
    return model.to(device).eval()

@torch.no_grad()
def predict_all(model, loader):
    ys, ps = [], []
    for x, y in loader:
        x = x.to(device)
        pred = model(x).argmax(1).cpu().numpy()
        ys.append(y.numpy()); ps.append(pred)
    return np.concatenate(ys), np.concatenate(ps)

eff_test = timm.create_model("efficientnet_b0", pretrained=False, num_classes=num_classes)
eff_test = load_best(eff_test, "/content/effb0_best.pt")

y_true, y_pred = predict_all(eff_test, test_loader)

print("EffNet TEST Accuracy:", accuracy_score(y_true, y_pred))
print("EffNet TEST Macro-F1:", f1_score(y_true, y_pred, average="macro"))

import torch
import torch.nn as nn

class SimpleCNN(nn.Module):
    def __init__(self, num_classes=8):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 32, 3, padding=1), nn.BatchNorm2d(32), nn.ReLU(),
            nn.MaxPool2d(2),  # 224 -> 112

            nn.Conv2d(32, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU(),
            nn.MaxPool2d(2),  # 112 -> 56

            nn.Conv2d(64, 128, 3, padding=1), nn.BatchNorm2d(128), nn.ReLU(),
            nn.MaxPool2d(2),  # 56 -> 28

            nn.Conv2d(128, 256, 3, padding=1), nn.BatchNorm2d(256), nn.ReLU(),
            nn.AdaptiveAvgPool2d((1,1))       # -> (256,1,1)
        )
        self.classifier = nn.Sequential(
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        x = self.features(x)
        x = x.flatten(1)
        return self.classifier(x)

num_classes = len(label_list)
cnn = SimpleCNN(num_classes=num_classes)
cnn

cnn_best = train_model_amp(
    cnn,
    train_loader,
    val_loader,
    epochs=5,
    lr=3e-4,
    save_path="/content/cnn_best.pt"
)

import numpy as np
from sklearn.metrics import accuracy_score, f1_score

# load best
cnn_test = SimpleCNN(num_classes=num_classes)
cnn_test = load_best(cnn_test, "/content/cnn_best.pt")  # uses your earlier load_best

y_true, y_pred = predict_all(cnn_test, test_loader)     # uses your earlier predict_all
print("CNN TEST Accuracy:", accuracy_score(y_true, y_pred))
print("CNN TEST Macro-F1:", f1_score(y_true, y_pred, average="macro"))

!pip -q install seaborn matplotlib

import torch, numpy as np, pandas as pd
import torch.nn as nn
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

def count_params(model):
    return sum(p.numel() for p in model.parameters()) / 1e6  # in millions

def load_ckpt(model, ckpt_path):
    ck = torch.load(ckpt_path, map_location="cpu")
    model.load_state_dict(ck["model"])
    return model.to(device).eval()

@torch.no_grad()
def predict_all(model, loader):
    ys, ps = [], []
    for x, y in loader:
        x = x.to(device)
        pred = model(x).argmax(1).cpu().numpy()
        ys.append(y.numpy()); ps.append(pred)
    return np.concatenate(ys), np.concatenate(ps)

def eval_model(model, loader, target_names):
    y_true, y_pred = predict_all(model, loader)
    acc = accuracy_score(y_true, y_pred)
    mf1 = f1_score(y_true, y_pred, average="macro")
    cm = confusion_matrix(y_true, y_pred)
    rep = classification_report(y_true, y_pred, target_names=target_names, digits=4)
    return acc, mf1, cm, rep

class SimpleCNN(nn.Module):
    def __init__(self, num_classes=8):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 32, 3, padding=1), nn.BatchNorm2d(32), nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(32, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(64, 128, 3, padding=1), nn.BatchNorm2d(128), nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(128, 256, 3, padding=1), nn.BatchNorm2d(256), nn.ReLU(),
            nn.AdaptiveAvgPool2d((1,1))
        )
        self.classifier = nn.Sequential(
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        x = self.features(x).flatten(1)
        return self.classifier(x)

num_classes = len(label_list)

cnn = SimpleCNN(num_classes=num_classes)
cnn = load_ckpt(cnn, "/content/cnn_best.pt")

import torchvision.models as tvm

resnet = tvm.resnet18(weights=None)
resnet.fc = nn.Linear(resnet.fc.in_features, num_classes)
resnet = load_ckpt(resnet, "/content/resnet18_best.pt")

import timm

eff = timm.create_model("efficientnet_b0", pretrained=False, num_classes=num_classes)
eff = load_ckpt(eff, "/content/effb0_best.pt")

results = []

for name, model in [("SimpleCNN", cnn), ("ResNet18", resnet), ("EfficientNet-B0", eff)]:
    acc, mf1, cm, rep = eval_model(model, test_loader, label_list)
    results.append({
        "Model": name,
        "Test Accuracy": acc,
        "Test Macro-F1": mf1,
        "Params (M)": count_params(model)
    })
    print("\n====", name, "====")
    print(rep)

comp_df = pd.DataFrame(results).sort_values("Test Macro-F1", ascending=False)
comp_df

def plot_cm(cm, title):
    plt.figure(figsize=(8,6))
    sns.heatmap(cm, cmap="Blues", xticklabels=label_list, yticklabels=label_list)
    plt.title(title)
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.tight_layout()
    plt.show()

# Compute and plot
for name, model in [("SimpleCNN", cnn), ("ResNet18", resnet), ("EfficientNet-B0", eff)]:
    acc, mf1, cm, _ = eval_model(model, test_loader, label_list)
    plot_cm(cm, f"{name} Confusion Matrix | Acc={acc:.3f} MacroF1={mf1:.3f}")

!pip -q install open_clip_torch faiss-cpu

import torch
import open_clip
from PIL import Image

device = "cuda" if torch.cuda.is_available() else "cpu"

clip_model, _, clip_preprocess = open_clip.create_model_and_transforms(
    "ViT-B-32", pretrained="laion2b_s34b_b79k"
)
clip_model = clip_model.to(device).eval()

print("CLIP ready on:", device)

import numpy as np
from tqdm import tqdm

# Use your df from earlier (path,label,y)
subset_df = df.sample(n=min(1000, len(df)), random_state=42).reset_index(drop=True)

@torch.no_grad()
def clip_embed_paths(paths, batch_size=64):
    embs = []
    for i in tqdm(range(0, len(paths), batch_size)):
        batch_paths = paths[i:i+batch_size]
        imgs = [clip_preprocess(Image.open(p).convert("RGB")) for p in batch_paths]
        x = torch.stack(imgs).to(device)
        f = clip_model.encode_image(x)
        f = f / f.norm(dim=-1, keepdim=True)          # normalize for cosine similarity
        embs.append(f.cpu().numpy().astype("float32"))
    return np.vstack(embs)

paths = subset_df["path"].tolist()
emb = clip_embed_paths(paths, batch_size=64)

emb.shape

import faiss
import numpy as np

D = emb.shape[1]
index = faiss.IndexFlatIP(D)
index.add(emb)

print("FAISS index size:", index.ntotal)

import random
from PIL import Image
import pandas as pd

@torch.no_grad()
def clip_embed_one(path):
    x = clip_preprocess(Image.open(path).convert("RGB")).unsqueeze(0).to(device)
    f = clip_model.encode_image(x)
    f = f / f.norm(dim=-1, keepdim=True)
    return f.cpu().numpy().astype("float32")

def recommend_similar(query_path, top_k=6):
    q = clip_embed_one(query_path)
    scores, idxs = index.search(q, top_k)
    recs = subset_df.iloc[idxs[0]].copy()
    recs["score"] = scores[0]
    return recs

query_path = random.choice(paths)
recs = recommend_similar(query_path, top_k=6)
recs[["label","score","path"]]

import matplotlib.pyplot as plt

def show_recs(query_path, top_k=5):
    recs = recommend_similar(query_path, top_k=top_k)
    plt.figure(figsize=(14,4))

    # Query image
    plt.subplot(1, top_k+1, 1)
    plt.imshow(Image.open(query_path).convert("RGB"))
    plt.axis("off")
    plt.title("QUERY")

    # Recommendations
    for i, row in enumerate(recs.itertuples(), start=2):
        plt.subplot(1, top_k+1, i)
        plt.imshow(Image.open(row.path).convert("RGB"))
        plt.axis("off")
        plt.title(f"{row.label}\n{row.score:.2f}")

    plt.tight_layout()
    plt.show()

show_recs(query_path, top_k=5)

from tqdm import tqdm
import numpy as np

all_df = df.reset_index(drop=True)
all_paths = all_df["path"].tolist()

emb_all = clip_embed_paths(all_paths, batch_size=64)
emb_all.shape

import os, faiss, pandas as pd

SAVE_DIR = "/content/fashion_reco_index"
os.makedirs(SAVE_DIR, exist_ok=True)

D = emb_all.shape[1]
index_all = faiss.IndexFlatIP(D)
index_all.add(emb_all)

faiss.write_index(index_all, f"{SAVE_DIR}/clip_faiss.index")
np.save(f"{SAVE_DIR}/clip_emb.npy", emb_all)
all_df[["path","label","y"]].to_csv(f"{SAVE_DIR}/meta.csv", index=False)

print("Saved to:", SAVE_DIR)
print("Index ntotal:", index_all.ntotal)

import faiss, numpy as np, pandas as pd
from PIL import Image
import random

index_all = faiss.read_index(f"{SAVE_DIR}/clip_faiss.index")
emb_all = np.load(f"{SAVE_DIR}/clip_emb.npy")
meta = pd.read_csv(f"{SAVE_DIR}/meta.csv")

def recommend_similar_all(query_path, top_k=6):
    q = clip_embed_one(query_path)
    scores, idxs = index_all.search(q, top_k)
    recs = meta.iloc[idxs[0]].copy()
    recs["score"] = scores[0]
    return recs

query_path = random.choice(meta["path"].tolist())
show_recs(query_path, top_k=5)  # uses your earlier show_recs but with subset index

import matplotlib.pyplot as plt

def show_recs_all(query_path, top_k=5):
    recs = recommend_similar_all(query_path, top_k=top_k)
    plt.figure(figsize=(14,4))

    plt.subplot(1, top_k+1, 1)
    plt.imshow(Image.open(query_path).convert("RGB"))
    plt.axis("off")
    plt.title("QUERY")

    for i, row in enumerate(recs.itertuples(), start=2):
        plt.subplot(1, top_k+1, i)
        plt.imshow(Image.open(row.path).convert("RGB"))
        plt.axis("off")
        plt.title(f"{row.label}\n{row.score:.2f}")

    plt.tight_layout()
    plt.show()

show_recs_all(query_path, top_k=5)

import pandas as pd

# load meta/index if not already in memory
meta = pd.read_csv("/content/fashion_reco_index/meta.csv")

TOP_CLASSES = {"casual_shirts", "formal_shirts", "printed_tshirts", "solid_tshirts", "printed_hoodies"}
BOTTOM_CLASSES = {"jeans", "formal_pants", "men_cargos"}

tops_df = meta[meta["label"].isin(TOP_CLASSES)].reset_index(drop=True)
bottoms_df = meta[meta["label"].isin(BOTTOM_CLASSES)].reset_index(drop=True)

len(tops_df), len(bottoms_df), tops_df["label"].value_counts(), bottoms_df["label"].value_counts()

import numpy as np
import faiss

emb_all = np.load("/content/fashion_reco_index/clip_emb.npy")

# Map from meta row -> embedding row (same order because we saved meta from all_df reset_index)
# So: embedding i corresponds to meta row i.

top_idx = tops_df.index.to_numpy()      # these are indices in tops_df, not meta
# We need indices in meta. Let's store meta row index first:
tops_meta_idx = meta.index[meta["label"].isin(TOP_CLASSES)].to_numpy()
bottoms_meta_idx = meta.index[meta["label"].isin(BOTTOM_CLASSES)].to_numpy()

emb_tops = emb_all[tops_meta_idx]
emb_bottoms = emb_all[bottoms_meta_idx]

D = emb_all.shape[1]
index_tops = faiss.IndexFlatIP(D); index_tops.add(emb_tops)
index_bottoms = faiss.IndexFlatIP(D); index_bottoms.add(emb_bottoms)

print("tops:", index_tops.ntotal, "bottoms:", index_bottoms.ntotal)

from PIL import Image
import matplotlib.pyplot as plt
import random

def recommend_bottoms_for_top(top_path, k=5):
    q = clip_embed_one(top_path)  # from earlier step (CLIP query embedding)
    scores, idxs = index_bottoms.search(q, k)
    # idxs are positions inside bottoms_meta_idx
    picked_meta_rows = bottoms_meta_idx[idxs[0]]
    recs = meta.iloc[picked_meta_rows].copy()
    recs["score"] = scores[0]
    return recs

# pick a random top as query
top_query_row = meta[meta["label"].isin(TOP_CLASSES)].sample(1, random_state=None).iloc[0]
top_path = top_query_row["path"]
top_label = top_query_row["label"]

recs = recommend_bottoms_for_top(top_path, k=5)
top_label, recs[["label","score","path"]]

def show_outfits_2piece(top_path, bottoms_recs):
    k = len(bottoms_recs)
    plt.figure(figsize=(3*(k+1), 6))

    # show top
    plt.subplot(1, k+1, 1)
    plt.imshow(Image.open(top_path).convert("RGB"))
    plt.axis("off")
    plt.title("TOP")

    # show bottoms
    for i, row in enumerate(bottoms_recs.itertuples(), start=2):
        plt.subplot(1, k+1, i)
        plt.imshow(Image.open(row.path).convert("RGB"))
        plt.axis("off")
        plt.title(f"{row.label}\n{row.score:.2f}")

    plt.tight_layout()
    plt.show()

show_outfits_2piece(top_path, recs)

def generate_outfits(n_outfits=3, bottoms_k=3):
    outfits = []
    top_candidates = meta[meta["label"].isin(TOP_CLASSES)].sample(n_outfits, random_state=None)

    for _, top_row in top_candidates.iterrows():
        top_path = top_row["path"]
        bottoms = recommend_bottoms_for_top(top_path, k=bottoms_k)
        outfits.append((top_row, bottoms))
    return outfits

outfits = generate_outfits(n_outfits=3, bottoms_k=3)
for top_row, bottoms in outfits:
    print("TOP:", top_row["label"], "|", top_row["path"])
    show_outfits_2piece(top_row["path"], bottoms)

from google.colab import drive
drive.mount("/content/drive")

!mkdir -p "/content/drive/MyDrive/fashion_models"
!cp /content/resnet18_best.pt "/content/drive/MyDrive/fashion_models/"
!cp /content/effb0_best.pt "/content/drive/MyDrive/fashion_models/"

import torch, torch.nn as nn
import torchvision.transforms as T
import torchvision.models as tvm
from PIL import Image
import timm
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"

eval_tf = T.Compose([
    T.Resize((224, 224)),
    T.ToTensor(),
    T.Normalize((0.485,0.456,0.406),(0.229,0.224,0.225))
])

def load_resnet18(num_classes, ckpt_path):
    m = tvm.resnet18(weights=None)
    m.fc = nn.Linear(m.fc.in_features, num_classes)
    ck = torch.load(ckpt_path, map_location="cpu")
    m.load_state_dict(ck["model"])
    return m.to(device).eval()

def load_effb0(num_classes, ckpt_path):
    m = timm.create_model("efficientnet_b0", pretrained=False, num_classes=num_classes)
    ck = torch.load(ckpt_path, map_location="cpu")
    m.load_state_dict(ck["model"])
    return m.to(device).eval()

@torch.no_grad()
def predict_proba(model, img_path):
    x = eval_tf(Image.open(img_path).convert("RGB")).unsqueeze(0).to(device)
    logits = model(x)
    prob = torch.softmax(logits, dim=1).cpu().numpy()[0]
    pred = int(prob.argmax())
    conf = float(prob.max())
    return pred, conf, prob

@torch.no_grad()
def predict_both_and_ensemble(img_path, resnet, effnet):
    x = eval_tf(Image.open(img_path).convert("RGB")).unsqueeze(0).to(device)
    lr = resnet(x)
    le = effnet(x)

    pr = torch.softmax(lr, 1)[0].detach().cpu().numpy()
    pe = torch.softmax(le, 1)[0].detach().cpu().numpy()

    # ensemble on logits
    p_ens = torch.softmax((lr + le)/2.0, 1)[0].detach().cpu().numpy()

    return pr, pe, p_ens

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torchvision.transforms as T
import torchvision.models as tvm
import timm
from PIL import Image

device = "cuda" if torch.cuda.is_available() else "cpu"

# class order must match training: we used sorted labels
meta = pd.read_csv("/content/fashion_reco_index/meta.csv")
label_list = sorted(meta["label"].unique().tolist())
label2id = {l:i for i,l in enumerate(label_list)}
id2label = {i:l for l,i in label2id.items()}
num_classes = len(label_list)
label_list

# same preprocessing used in training
eval_tf = T.Compose([
    T.Resize((224, 224)),
    T.ToTensor(),
    T.Normalize((0.485,0.456,0.406),(0.229,0.224,0.225))
])

def load_ckpt(model, ckpt_path):
    ck = torch.load(ckpt_path, map_location="cpu")
    model.load_state_dict(ck["model"])
    return model.to(device).eval()

# ResNet18
resnet = tvm.resnet18(weights=None)
resnet.fc = nn.Linear(resnet.fc.in_features, num_classes)
resnet = load_ckpt(resnet, "/content/resnet18_best.pt")

# EfficientNet-B0
effnet = timm.create_model("efficientnet_b0", pretrained=False, num_classes=num_classes)
effnet = load_ckpt(effnet, "/content/effb0_best.pt")

print("Models loaded.")

import open_clip
import faiss

clip_model, _, clip_preprocess = open_clip.create_model_and_transforms(
    "ViT-B-32", pretrained="laion2b_s34b_b79k"
)
clip_model = clip_model.to(device).eval()

index_all = faiss.read_index("/content/fashion_reco_index/clip_faiss.index")
meta = pd.read_csv("/content/fashion_reco_index/meta.csv")  # reload to be safe

print("CLIP + FAISS loaded. Index size:", index_all.ntotal)

import matplotlib.pyplot as plt

TOP_CLASSES = {"casual_shirts", "formal_shirts", "printed_tshirts", "solid_tshirts", "printed_hoodies"}
BOTTOM_CLASSES = {"jeans", "formal_pants", "men_cargos"}

@torch.no_grad()
def classify_both(img_path):
    x = eval_tf(Image.open(img_path).convert("RGB")).unsqueeze(0).to(device)

    lr = resnet(x)
    le = effnet(x)

    pr = torch.softmax(lr, 1)[0].detach().cpu().numpy()
    pe = torch.softmax(le, 1)[0].detach().cpu().numpy()
    pens = torch.softmax((lr + le) / 2.0, 1)[0].detach().cpu().numpy()

    def pack(p):
        pred_id = int(p.argmax())
        return {
            "pred_id": pred_id,
            "pred_label": id2label[pred_id],
            "conf": float(p.max()),
            "probs": p
        }

    return pack(pr), pack(pe), pack(pens)

@torch.no_grad()
def clip_embed_one(path):
    x = clip_preprocess(Image.open(path).convert("RGB")).unsqueeze(0).to(device)
    f = clip_model.encode_image(x)
    f = f / f.norm(dim=-1, keepdim=True)
    return f.cpu().numpy().astype("float32")

def recommend_by_category(query_img_path, target_classes, top_k=5, search_k=80):
    """
    Search FAISS globally, then filter results to target_classes.
    search_k should be > top_k to allow filtering.
    """
    q = clip_embed_one(query_img_path)
    scores, idxs = index_all.search(q, search_k)

    recs = meta.iloc[idxs[0]].copy()
    recs["score"] = scores[0]

    # filter by category + remove same image
    recs = recs[recs["label"].isin(target_classes)]
    recs = recs[recs["path"] != query_img_path]

    return recs.head(top_k).reset_index(drop=True)

def show_outfit_2piece(top_path, bottoms_df, title="Outfit suggestions"):
    k = len(bottoms_df)
    plt.figure(figsize=(3*(k+1), 5))

    plt.subplot(1, k+1, 1)
    plt.imshow(Image.open(top_path).convert("RGB"))
    plt.axis("off")
    plt.title("INPUT")

    for i, row in enumerate(bottoms_df.itertuples(), start=2):
        plt.subplot(1, k+1, i)
        plt.imshow(Image.open(row.path).convert("RGB"))
        plt.axis("off")
        plt.title(f"{row.label}\n{row.score:.2f}")

    plt.suptitle(title)
    plt.tight_layout()
    plt.show()

def demo(img_path, classifier_choice="ensemble", reco_k=5):
    """
    classifier_choice: 'resnet' | 'effnet' | 'ensemble'
    """
    r, e, ens = classify_both(img_path)

    print("ResNet18 :", r["pred_label"], "| conf:", round(r["conf"], 4))
    print("EffNet-B0:", e["pred_label"], "| conf:", round(e["conf"], 4))
    print("Ensemble :", ens["pred_label"], "| conf:", round(ens["conf"], 4))

    chosen = {"resnet": r, "effnet": e, "ensemble": ens}[classifier_choice]
    pred_label = chosen["pred_label"]

    # Decide recommendation direction
    if pred_label in TOP_CLASSES:
        recs = recommend_by_category(img_path, BOTTOM_CLASSES, top_k=reco_k)
        show_outfit_2piece(img_path, recs, title=f"Input TOP → Recommended BOTTOMS (using {classifier_choice})")
    elif pred_label in BOTTOM_CLASSES:
        recs = recommend_by_category(img_path, TOP_CLASSES, top_k=reco_k)
        show_outfit_2piece(img_path, recs, title=f"Input BOTTOM → Recommended TOPS (using {classifier_choice})")
    else:
        # fallback: just show similar items
        recs = recommend_by_category(img_path, set(label_list), top_k=reco_k)
        show_outfit_2piece(img_path, recs, title=f"Input → Similar items (using {classifier_choice})")

    return chosen, recs

import random

img_path = random.choice(meta["path"].tolist())
chosen, recs = demo(img_path, classifier_choice="ensemble", reco_k=5)

img_path = "/content/mens-shirts.jpg"
demo(img_path, classifier_choice="ensemble", reco_k=5)

img_path = "/content/mens-shirts.jpg"

import os
assert os.path.exists(img_path), f"File not found: {img_path}"

from PIL import Image
import matplotlib.pyplot as plt

# show the image first
plt.figure(figsize=(4,4))
plt.imshow(Image.open(img_path).convert("RGB"))
plt.axis("off")
plt.title("Input image")
plt.show()

# run your classifier + outfit recommendation demo
demo(img_path, classifier_choice="ensemble", reco_k=5)

import numpy as np, faiss, pandas as pd

meta = pd.read_csv("/content/fashion_reco_index/meta.csv")
emb_all = np.load("/content/fashion_reco_index/clip_emb.npy")

TOP_CLASSES = {"casual_shirts", "formal_shirts", "printed_tshirts", "solid_tshirts", "printed_hoodies"}
BOTTOM_CLASSES = {"jeans", "formal_pants", "men_cargos"}

bottoms_meta_idx = meta.index[meta["label"].isin(BOTTOM_CLASSES)].to_numpy()
emb_bottoms = emb_all[bottoms_meta_idx].astype("float32")

D = emb_bottoms.shape[1]
index_bottoms = faiss.IndexFlatIP(D)
index_bottoms.add(emb_bottoms)

print("Bottom index size:", index_bottoms.ntotal)

def recommend_bottoms_direct(query_img_path, k=5):
    q = clip_embed_one(query_img_path)              # uses CLIP query embedding
    scores, idxs = index_bottoms.search(q, k)       # idxs are within bottom index
    picked_meta_rows = bottoms_meta_idx[idxs[0]]    # map back to meta rows

    recs = meta.iloc[picked_meta_rows].copy()
    recs["score"] = scores[0]
    return recs.reset_index(drop=True)

recs = recommend_bottoms_direct("/content/mens-shirts.jpg", k=5)
recs[["label","score","path"]]

show_outfit_2piece("/content/mens-shirts.jpg", recs, title="Input TOP → Recommended BOTTOMS (bottom-only index)")

!pip -q install opencv-python scikit-learn

import cv2, numpy as np
from sklearn.cluster import KMeans
from PIL import Image

def dominant_rgb(img_path, k=3, resize=160):
    img = np.array(Image.open(img_path).convert("RGB"))
    h, w = img.shape[:2]
    scale = resize / max(h, w)
    img = cv2.resize(img, (int(w*scale), int(h*scale)))
    X = img.reshape(-1, 3)

    km = KMeans(n_clusters=k, n_init="auto", random_state=42).fit(X)
    centers = km.cluster_centers_.astype(int)
    counts = np.bincount(km.labels_)
    dom = centers[counts.argmax()]
    return dom  # [R,G,B]

def rgb_to_hsv(rgb):
    rgb = np.uint8([[rgb]])
    hsv = cv2.cvtColor(rgb, cv2.COLOR_RGB2HSV)[0][0]
    return hsv  # [H(0-179), S(0-255), V(0-255)]

def color_harmony_score(rgb1, rgb2):
    # simple hue distance + preference for neutral bottoms
    h1,s1,v1 = rgb_to_hsv(rgb1)
    h2,s2,v2 = rgb_to_hsv(rgb2)
    hue_dist = min(abs(int(h1)-int(h2)), 180-abs(int(h1)-int(h2))) / 90.0  # 0..1 roughly
    neutral_bonus = 0.2 if s2 < 50 else 0.0  # low saturation bottom = neutral
    return float(1.0 - hue_dist + neutral_bonus)

top_rgb = dominant_rgb("/content/mens-shirts.jpg")

recs2 = recs.copy()
recs2["bottom_rgb"] = recs2["path"].apply(dominant_rgb)
recs2["color_score"] = recs2["bottom_rgb"].apply(lambda c: color_harmony_score(top_rgb, c))

# combine with CLIP similarity score you already have
recs2["final_score"] = 0.7*recs2["score"] + 0.3*recs2["color_score"]
recs2 = recs2.sort_values("final_score", ascending=False)

recs2[["label","score","color_score","final_score","path"]].head(5)

import open_clip, torch
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"

tokenizer = open_clip.get_tokenizer("ViT-B-32")

@torch.no_grad()
def clip_text_embed(texts):
    tokens = tokenizer(texts).to(device)
    t = clip_model.encode_text(tokens)
    t = t / t.norm(dim=-1, keepdim=True)
    return t.cpu().numpy().astype("float32")

BOTTOM_PROMPTS = {
    "casual": [
        "men's casual jeans",
        "men's casual cargo pants",
        "men's casual pants outfit"
    ],
    "formal": [
        "men's formal pants",
        "men's office formal trousers",
        "business formal men's pants"
    ],
    "streetwear": [
        "men's streetwear cargos",
        "streetwear men's jeans",
        "urban streetwear pants"
    ]
}

text_embeds = {k: clip_text_embed(v) for k,v in BOTTOM_PROMPTS.items()}
{k: v.shape for k,v in text_embeds.items()}

# If you already created index_bottoms/bottoms_meta_idx earlier, keep it.
# If not, run this once:

import pandas as pd, faiss

meta = pd.read_csv("/content/fashion_reco_index/meta.csv")
emb_all = np.load("/content/fashion_reco_index/clip_emb.npy")

BOTTOM_CLASSES = {"jeans", "formal_pants", "men_cargos"}
bottoms_meta_idx = meta.index[meta["label"].isin(BOTTOM_CLASSES)].to_numpy()
emb_bottoms = emb_all[bottoms_meta_idx].astype("float32")

D = emb_bottoms.shape[1]
index_bottoms = faiss.IndexFlatIP(D)
index_bottoms.add(emb_bottoms)

print("Bottom index size:", index_bottoms.ntotal)

def recommend_bottoms_hybrid(top_img_path, occasion="casual", k=5, search_k=50,
                             w_img=0.75, w_txt=0.25):
    """
    w_img: weight for image-image compatibility (CLIP image similarity)
    w_txt: weight for bottom matching the occasion prompt (CLIP text similarity)
    """
    # 1) retrieve candidate bottoms by image similarity
    q_img = clip_embed_one(top_img_path)  # (1,512)
    img_scores, idxs = index_bottoms.search(q_img, search_k)

    picked_meta_rows = bottoms_meta_idx[idxs[0]]
    cand = meta.iloc[picked_meta_rows].copy()
    cand["img_score"] = img_scores[0]

    # 2) text score: compare candidate bottom image embeddings to averaged prompt embedding
    occ = occasion.lower().strip()
    if occ not in text_embeds:
        occ = "casual"

    prompt_vec = text_embeds[occ].mean(axis=0, keepdims=True)  # (1,512), already normalized-ish
    prompt_vec = prompt_vec / np.linalg.norm(prompt_vec, axis=1, keepdims=True)

    cand_emb = emb_all[picked_meta_rows]  # (search_k,512)
    txt_score = (cand_emb @ prompt_vec.T).reshape(-1)  # cosine because normalized
    cand["txt_score"] = txt_score

    # 3) combine
    cand["final_score"] = w_img*cand["img_score"] + w_txt*cand["txt_score"]
    cand = cand.sort_values("final_score", ascending=False).head(k).reset_index(drop=True)
    return cand[["path","label","img_score","txt_score","final_score"]]

top_path = "/content/mens-shirts.jpg"
recs_h = recommend_bottoms_hybrid(top_path, occasion="casual", k=5, search_k=80)
recs_h

show_outfit_2piece(top_path, recs_h.rename(columns={"final_score":"score"}),
                   title="Top → Bottoms (Image similarity + CLIP text occasion)")

!pip -q install opencv-python-headless

import cv2, numpy as np
from PIL import Image

def clothing_color_stats(img_path, resize=180):
    """
    Returns (h,s,v) mean of 'non-background' pixels in HSV.
    We drop near-white/low-saturation pixels to avoid background dominating.
    """
    img = np.array(Image.open(img_path).convert("RGB"))
    h, w = img.shape[:2]
    scale = resize / max(h, w)
    img = cv2.resize(img, (int(w*scale), int(h*scale)))

    hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)
    H, S, V = hsv[:,:,0], hsv[:,:,1], hsv[:,:,2]

    # keep pixels that are not "white background"
    mask = (S > 35) & (V < 245)  # tune if needed
    if mask.sum() < 200:         # fallback if mask too small
        mask = np.ones_like(S, dtype=bool)

    h_mean = float(H[mask].mean())
    s_mean = float(S[mask].mean())
    v_mean = float(V[mask].mean())
    return h_mean, s_mean, v_mean

def hue_dist(h1, h2):
    d = abs(h1 - h2)
    return min(d, 180 - d)  # hue is 0..179 in OpenCV

def color_harmony_score(top_stats, bottom_stats):
    """
    Simple stylist rule:
    - If top is colorful (high saturation), prefer neutral bottoms (low saturation)
    - If top is neutral, allow more color
    - Prefer some value contrast (not same brightness)
    Returns score ~0..1+
    """
    ht, st, vt = top_stats
    hb, sb, vb = bottom_stats

    # bottom neutrality bonus (good for most outfits)
    neutral_bonus = 1.0 - min(sb/255.0, 1.0)  # low saturation => higher bonus

    # if top is colorful, strongly prefer neutral bottoms
    top_colorful = (st > 90)
    if top_colorful:
        neutral_bonus = neutral_bonus * 1.3

    # brightness contrast (avoid too similar brightness)
    v_contrast = min(abs(vt - vb)/255.0, 1.0)

    # mild hue penalty (only matters when bottoms are also colorful)
    hue_penalty = (hue_dist(ht, hb)/90.0) * (sb/255.0)  # colorful bottom => penalty matters more

    score = 0.55*neutral_bonus + 0.35*v_contrast - 0.20*hue_penalty
    return float(score)

top_path = "/content/mens-shirts.jpg"

top_stats = clothing_color_stats(top_path)
print("Top HSV stats (H,S,V):", top_stats)

recs_color = recs_h.copy()
recs_color["bottom_stats"] = recs_color["path"].apply(clothing_color_stats)
recs_color["color_score"] = recs_color["bottom_stats"].apply(lambda b: color_harmony_score(top_stats, b))

# Combine: keep your hybrid CLIP score as main, color as re-ranker
# (you can change weights later)
recs_color["final2_score"] = 0.75*recs_color["final_score"] + 0.25*recs_color["color_score"]

recs_color = recs_color.sort_values("final2_score", ascending=False).reset_index(drop=True)
recs_color[["label","img_score","txt_score","final_score","color_score","final2_score"]]

show_outfit_2piece(
    top_path,
    recs_color.rename(columns={"final2_score":"score"}),
    title="Top → Bottoms (Image+Text + Color Harmony re-ranking)"
)

import numpy as np
import torch
import open_clip

tokenizer = open_clip.get_tokenizer("ViT-B-32")

@torch.no_grad()
def clip_text_embed_one(text: str):
    tokens = tokenizer([text]).to(device)
    t = clip_model.encode_text(tokens)
    t = t / t.norm(dim=-1, keepdim=True)
    return t.cpu().numpy().astype("float32")  # (1,512)

def recommend_bottoms_free_text(top_img_path, occasion_text, k=5, search_k=80,
                                w_img=0.70, w_txt=0.30):
    """
    occasion_text: user input like 'wedding', 'office', 'gym', 'date night', etc.
    """
    occasion_text = (occasion_text or "").strip()
    if len(occasion_text) == 0:
        occasion_text = "casual everyday"

    # 1) retrieve candidate bottoms by image similarity
    q_img = clip_embed_one(top_img_path)
    img_scores, idxs = index_bottoms.search(q_img, search_k)

    picked_meta_rows = bottoms_meta_idx[idxs[0]]
    cand = meta.iloc[picked_meta_rows].copy()
    cand["img_score"] = img_scores[0]

    # 2) text score: use templates to make the prompt more clothing-specific
    templates = [
        f"men's {occasion_text} outfit pants",
        f"men's {occasion_text} trousers",
        f"men's {occasion_text} jeans outfit",
    ]
    t = np.mean([clip_text_embed_one(t) for t in templates], axis=0)  # (1,512)
    t = t / np.linalg.norm(t, axis=1, keepdims=True)

    cand_emb = emb_all[picked_meta_rows]         # (search_k,512) already normalized
    cand["txt_score"] = (cand_emb @ t.T).reshape(-1)

    # 3) combine
    cand["final_score"] = w_img*cand["img_score"] + w_txt*cand["txt_score"]
    cand = cand.sort_values("final_score", ascending=False).head(k).reset_index(drop=True)

    return cand[["path","label","img_score","txt_score","final_score"]]

top_path = "/content/mens-shirts.jpg"

occasion_text = "office meeting"   # try: "wedding", "college party", "date night", "interview"
recs_free = recommend_bottoms_free_text(top_path, occasion_text, k=5, search_k=100)
recs_free

show_outfit_2piece(
    top_path,
    recs_free.rename(columns={"final_score":"score"}),
    title=f"Top → Bottoms (occasion: {occasion_text})"
)

!pip -q install facenet-pytorch opencv-python-headless pillow

import torch
import cv2
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from facenet_pytorch import MTCNN

device = "cuda" if torch.cuda.is_available() else "cpu"
mtcnn = MTCNN(keep_all=True, device=device)   # keep_all=True, we'll choose best face
print("Device:", device)

def clamp(v, lo, hi):
    return max(lo, min(hi, v))

def skin_mask_ycrcb(roi_bgr):
    """Basic skin pixel mask in YCrCb."""
    ycrcb = cv2.cvtColor(roi_bgr, cv2.COLOR_BGR2YCrCb)
    Y, Cr, Cb = cv2.split(ycrcb)
    mask = (Cr >= 133) & (Cr <= 173) & (Cb >= 77) & (Cb <= 127)
    mask = mask & (Y > 30) & (Y < 245)
    return mask

def face_and_cheeks_bboxes(img_bgr, face_xyxy):
    """Given face bbox (x1,y1,x2,y2), return face + left/right cheek boxes as (x,y,w,h)."""
    h, w = img_bgr.shape[:2]
    x1, y1, x2, y2 = [int(v) for v in face_xyxy]
    x1 = clamp(x1, 0, w-2); y1 = clamp(y1, 0, h-2)
    x2 = clamp(x2, x1+2, w); y2 = clamp(y2, y1+2, h)

    bw, bh = x2-x1, y2-y1
    face = (x1, y1, bw, bh)

    # cheek regions (heuristic inside face box)
    cy1 = y1 + int(0.45 * bh)
    cy2 = y1 + int(0.70 * bh)

    lx1 = x1 + int(0.15 * bw); lx2 = x1 + int(0.40 * bw)
    rx1 = x1 + int(0.60 * bw); rx2 = x1 + int(0.85 * bw)

    left  = (lx1, cy1, max(2, lx2-lx1), max(2, cy2-cy1))
    right = (rx1, cy1, max(2, rx2-rx1), max(2, cy2-cy1))
    return face, left, right

def crop_xywh(img_bgr, bb):
    x,y,w,h = bb
    return img_bgr[y:y+h, x:x+w].copy()

def estimate_skin_profile(face_img_path, show=True):
    """
    Output:
      tone: light/medium/deep (approx)
      undertone: warm/cool/neutral (approx)
    """
    img_rgb = np.array(Image.open(face_img_path).convert("RGB"))
    img_bgr = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2BGR)

    boxes, probs = mtcnn.detect(Image.fromarray(img_rgb))
    if boxes is None or len(boxes) == 0:
        raise ValueError("No face detected. Use a clearer front-facing photo with good lighting.")

    # choose the face with highest probability
    best_i = int(np.argmax(probs))
    face_xyxy = boxes[best_i]

    face_bb, left_bb, right_bb = face_and_cheeks_bboxes(img_bgr, face_xyxy)
    left_roi  = crop_xywh(img_bgr, left_bb)
    right_roi = crop_xywh(img_bgr, right_bb)

    pixels = []
    for roi in [left_roi, right_roi]:
        if roi.size == 0:
            continue
        mask = skin_mask_ycrcb(roi)
        if mask.sum() < 80:  # fallback if mask weak
            mask = np.ones(mask.shape, dtype=bool)
        pixels.append(roi[mask])

    if len(pixels) == 0:
        raise ValueError("Could not sample cheek regions. Try another photo.")

    pixels = np.vstack(pixels).astype(np.uint8)  # BGR pixels

    # Lab: L (lightness) for tone, b channel for warm/cool tendency (yellow-blue)
    lab = cv2.cvtColor(pixels.reshape(-1,1,3), cv2.COLOR_BGR2LAB).reshape(-1,3)
    L_mean, a_mean, b_mean = lab.mean(axis=0)
    delta_b = b_mean - 128

    if delta_b > 6:
        undertone = "warm"
    elif delta_b < -6:
        undertone = "cool"
    else:
        undertone = "neutral"

    if L_mean >= 170:
        tone = "light"
    elif L_mean >= 130:
        tone = "medium"
    else:
        tone = "deep"

    profile = {
        "tone": tone,
        "undertone": undertone,
        "L_mean": float(L_mean),
        "a_mean": float(a_mean),
        "b_mean": float(b_mean),
        "face_bb": face_bb,
        "left_cheek_bb": left_bb,
        "right_cheek_bb": right_bb
    }

    if show:
        vis = img_rgb.copy()
        for (x,y,w,h), color, name in [
            (face_bb, (0,255,0), "face"),
            (left_bb, (255,0,0), "L cheek"),
            (right_bb, (0,0,255), "R cheek")
        ]:
            cv2.rectangle(vis, (x,y), (x+w,y+h), color, 2)
            cv2.putText(vis, name, (x, max(0, y-8)), cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)

        plt.figure(figsize=(6,6))
        plt.imshow(vis)
        plt.axis("off")
        plt.title(f"tone={tone}, undertone={undertone} | L={L_mean:.1f}, b-128={delta_b:.1f}")
        plt.show()

    return profile

from google.colab import files
uploaded = files.upload()
face_img_path = "/content/" + list(uploaded.keys())[0]

skin_profile = estimate_skin_profile(face_img_path, show=True)
skin_profile

def palette_from_undertone(undertone):
    if undertone == "warm":
        return ["olive", "mustard", "camel", "cream", "rust", "chocolate", "warm navy"]
    if undertone == "cool":
        return ["cobalt", "emerald", "burgundy", "charcoal", "pure white", "navy", "plum"]
    return ["navy", "white", "black", "gray", "denim", "earth tones", "jewel tones"]

print("Detected:", skin_profile["tone"], skin_profile["undertone"])
print("Suggested palette:", palette_from_undertone(skin_profile["undertone"]))

import cv2
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

def rgb_to_hex(rgb):
    r, g, b = [int(x) for x in rgb]
    return "#{:02x}{:02x}{:02x}".format(r, g, b)

def detailed_tone_from_L(L):
    """
    Lab L in OpenCV is 0-255.
    This is approximate and lighting-dependent.
    """
    if L >= 190:
        return "very light"
    elif L >= 170:
        return "light"
    elif L >= 135:
        return "medium"
    elif L >= 110:
        return "tan"
    elif L >= 85:
        return "deep"
    else:
        return "very deep"

def undertone_from_lab_b(b_mean):
    """
    OpenCV Lab b channel:
    >128 more yellow/warm
    <128 more blue/cool
    """
    delta = b_mean - 128

    if delta > 10:
        undertone = "warm"
        strength = "strong"
    elif delta > 5:
        undertone = "warm"
        strength = "mild"
    elif delta < -10:
        undertone = "cool"
        strength = "strong"
    elif delta < -5:
        undertone = "cool"
        strength = "mild"
    else:
        undertone = "neutral"
        strength = "balanced"

    return undertone, strength, float(delta)

def skin_description(tone_detail, undertone, strength):
    if undertone == "warm":
        if strength == "strong":
            return f"{tone_detail} warm golden"
        return f"{tone_detail} warm beige"
    elif undertone == "cool":
        if strength == "strong":
            return f"{tone_detail} cool rosy"
        return f"{tone_detail} cool beige"
    else:
        return f"{tone_detail} neutral beige"

def approximate_face_shape(face_bb, landmarks=None):
    """
    Very rough face shape estimate.
    With MTCNN we only have 5 landmarks, not full jawline.
    So this is approximate, not final.
    """
    x, y, w, h = face_bb
    ratio = h / max(w, 1)

    # Basic shape from height/width ratio
    if ratio >= 1.55:
        shape = "long / oblong"
    elif ratio >= 1.35:
        shape = "oval"
    elif ratio >= 1.18:
        shape = "round / soft oval"
    else:
        shape = "square / round"

    return shape, float(ratio)

def palette_from_skin_profile(undertone, tone_detail):
    """
    Practical fashion color suggestions.
    """
    if undertone == "warm":
        best = [
            "olive green", "mustard", "camel", "cream", "rust",
            "chocolate brown", "warm navy", "beige", "terracotta"
        ]
        avoid = [
            "icy blue", "very cool gray", "neon purple", "blue-heavy pastels"
        ]
    elif undertone == "cool":
        best = [
            "cobalt blue", "emerald", "burgundy", "charcoal",
            "pure white", "navy", "plum", "cool gray", "black"
        ]
        avoid = [
            "mustard", "orange brown", "yellow beige", "rust orange"
        ]
    else:
        best = [
            "navy", "white", "black", "gray", "denim blue",
            "earth tones", "jewel tones", "cream"
        ]
        avoid = []

    # Small adjustment by tone depth
    if tone_detail in ["deep", "very deep"]:
        best += ["bright white", "royal blue", "deep red", "emerald"]
    elif tone_detail in ["very light", "light"]:
        best += ["soft navy", "rose", "sage green", "light denim"]

    return {
        "best_colors": best,
        "avoid_colors": avoid
    }

def estimate_skin_profile_detailed(face_img_path, show=True):
    img_rgb = np.array(Image.open(face_img_path).convert("RGB"))
    img_bgr = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2BGR)

    # MTCNN face detection with landmarks
    boxes, probs, landmarks = mtcnn.detect(Image.fromarray(img_rgb), landmarks=True)

    if boxes is None or len(boxes) == 0:
        raise ValueError("No face detected. Use a clearer front-facing photo with good lighting.")

    best_i = int(np.argmax(probs))
    face_xyxy = boxes[best_i]
    face_lm = landmarks[best_i] if landmarks is not None else None

    face_bb, left_bb, right_bb = face_and_cheeks_bboxes(img_bgr, face_xyxy)

    left_roi = crop_xywh(img_bgr, left_bb)
    right_roi = crop_xywh(img_bgr, right_bb)

    pixels = []
    for roi in [left_roi, right_roi]:
        if roi.size == 0:
            continue

        mask = skin_mask_ycrcb(roi)

        if mask.sum() < 80:
            mask = np.ones(mask.shape, dtype=bool)

        pixels.append(roi[mask])

    if len(pixels) == 0:
        raise ValueError("Could not sample cheek pixels. Try another face image.")

    pixels = np.vstack(pixels).astype(np.uint8)  # BGR pixels

    # Mean color
    mean_bgr = pixels.mean(axis=0)
    mean_rgb = mean_bgr[::-1]  # BGR -> RGB
    mean_hex = rgb_to_hex(mean_rgb)

    # Lab analysis
    lab = cv2.cvtColor(pixels.reshape(-1, 1, 3), cv2.COLOR_BGR2LAB).reshape(-1, 3)
    L_mean, a_mean, b_mean = lab.mean(axis=0)

    tone_detail = detailed_tone_from_L(L_mean)
    undertone, undertone_strength, delta_b = undertone_from_lab_b(b_mean)
    desc = skin_description(tone_detail, undertone, undertone_strength)

    # Face shape estimate
    face_shape, face_ratio = approximate_face_shape(face_bb, face_lm)

    palette = palette_from_skin_profile(undertone, tone_detail)

    profile = {
        "tone_detail": tone_detail,
        "undertone": undertone,
        "undertone_strength": undertone_strength,
        "skin_description": desc,
        "estimated_skin_rgb": [int(x) for x in mean_rgb],
        "estimated_skin_hex": mean_hex,
        "L_mean": float(L_mean),
        "a_mean": float(a_mean),
        "b_mean": float(b_mean),
        "b_minus_128": float(delta_b),
        "approx_face_shape": face_shape,
        "face_ratio_h_over_w": face_ratio,
        "recommended_palette": palette,
        "face_bb": face_bb,
        "left_cheek_bb": left_bb,
        "right_cheek_bb": right_bb,
    }

    if show:
        vis = img_rgb.copy()

        # Draw face + cheeks
        for (x, y, w, h), color, name in [
            (face_bb, (0, 255, 0), "face"),
            (left_bb, (255, 0, 0), "L cheek"),
            (right_bb, (0, 0, 255), "R cheek")
        ]:
            cv2.rectangle(vis, (x, y), (x+w, y+h), color, 2)
            cv2.putText(vis, name, (x, max(0, y-8)),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.55, color, 2)

        # Draw landmarks if available
        if face_lm is not None:
            for px, py in face_lm:
                cv2.circle(vis, (int(px), int(py)), 3, (255, 255, 0), -1)

        plt.figure(figsize=(12, 5))

        plt.subplot(1, 2, 1)
        plt.imshow(vis)
        plt.axis("off")
        plt.title(
            f"{desc}\nFace shape: {face_shape}\nHEX: {mean_hex}"
        )

        # Color swatch
        swatch = np.ones((200, 300, 3), dtype=np.uint8)
        swatch[:, :] = np.array(mean_rgb, dtype=np.uint8)

        plt.subplot(1, 2, 2)
        plt.imshow(swatch)
        plt.axis("off")
        plt.title(f"Estimated skin color\nRGB={profile['estimated_skin_rgb']}\nHEX={mean_hex}")

        plt.tight_layout()
        plt.show()

    return profile

face_img_path = "/content/gettyimages-1067600766-612x612.jpg"

skin_profile_detailed = estimate_skin_profile_detailed(face_img_path, show=True)
skin_profile_detailed

def color_family_from_hsv(h, s, v):
    # neutral if low saturation (gray/black/white/denim-like)
    if s < 45:
        return "neutral"
    # warm hues: red/orange/yellow/olive-ish
    if (h <= 35) or (h >= 160) or (35 < h <= 80):
        return "warm"
    # otherwise treat as cool (green/cyan/blue/purple range)
    return "cool"

def skin_match_score(item_hsv_stats, undertone):
    """
    Returns 0..1 score.
    Neutral colors work for everyone, so they score high.
    """
    h, s, v = item_hsv_stats
    fam = color_family_from_hsv(h, s, v)

    if fam == "neutral":
        return 0.95
    if undertone == "neutral":
        return 0.80
    return 1.00 if fam == undertone else 0.45

def recommend_bottoms_personalized(top_img_path, occasion_text, skin_profile, k=5, search_k=120,
                                  w_clip=0.60, w_harmony=0.20, w_skin=0.20):
    """
    Uses:
    - recommend_bottoms_free_text() -> gives img_score/txt_score/final_score (CLIP image+text)
    - color_harmony_score(top,bottom)
    - skin_match_score(bottom, user undertone)
    """
    # 1) base candidates from CLIP (image+text)
    cand = recommend_bottoms_free_text(top_img_path, occasion_text, k=max(k, 10), search_k=search_k).copy()

    # 2) compute bottom HSV stats
    cand["bottom_hsv"] = cand["path"].apply(clothing_color_stats)

    # 3) harmony with the top
    top_hsv = clothing_color_stats(top_img_path)
    cand["harmony_score"] = cand["bottom_hsv"].apply(lambda b: color_harmony_score(top_hsv, b))

    # 4) skin-tone match
    undertone = skin_profile["undertone"]
    cand["skin_score"] = cand["bottom_hsv"].apply(lambda st: skin_match_score(st, undertone))

    # 5) final score (combine)
    cand["final_personal"] = (
        w_clip * cand["final_score"] +
        w_harmony * cand["harmony_score"] +
        w_skin * cand["skin_score"]
    )

    cand = cand.sort_values("final_personal", ascending=False).head(k).reset_index(drop=True)
    return cand

top_path = "/content/mens-shirts.jpg"
occasion_text = "office meeting"   # user can type ANY occasion text

recs_p = recommend_bottoms_personalized(
    top_path,
    occasion_text,
    skin_profile_detailed,
    k=5
)

recs_p[["label","img_score","txt_score","harmony_score","skin_score","final_personal"]]

show_outfit_2piece(
    top_path,
    recs_p.rename(columns={"final_personal":"score"}),
    title=f"Personalized bottoms | occasion='{occasion_text}' | undertone={skin_profile_detailed['undertone']}"
)

!pip -q install ultralytics opencv-python-headless

from google.colab import files
uploaded = files.upload()
person_path = "/content/" + list(uploaded.keys())[0]
person_path

import cv2, numpy as np
import matplotlib.pyplot as plt
from ultralytics import YOLO

pose_model = YOLO("yolov8n-pose.pt")  # small + fast

img_bgr = cv2.imread(person_path)
if img_bgr is None:
    raise ValueError("Could not read image. Check the file path.")
H, W = img_bgr.shape[:2]

res = pose_model.predict(person_path, conf=0.25, verbose=False)[0]

if res.keypoints is None or len(res.keypoints) == 0:
    raise ValueError("No person keypoints detected. Try a clearer full-body image.")

# choose the best detection (highest box confidence)
boxes_conf = res.boxes.conf.cpu().numpy()
best_i = int(np.argmax(boxes_conf))

kpts = res.keypoints.xy[best_i].cpu().numpy()  # (17,2) in COCO order

# COCO keypoint indices:
L_SH, R_SH = 5, 6
L_HIP, R_HIP = 11, 12
L_ANK, R_ANK = 15, 16

def clamp(v, lo, hi):
    return int(max(lo, min(hi, v)))

def safe_xy(points):
    # keep only valid points (non-zero-ish)
    pts = points.copy()
    good = ~np.isnan(pts[:,0]) & ~np.isnan(pts[:,1]) & (pts[:,0] > 1) & (pts[:,1] > 1)
    return pts[good] if good.any() else pts

shoulders = safe_xy(kpts[[L_SH, R_SH]])
hips      = safe_xy(kpts[[L_HIP, R_HIP]])
ankles    = safe_xy(kpts[[L_ANK, R_ANK]])

# fallback if something missing: use bounding box
x1, y1, x2, y2 = res.boxes.xyxy[best_i].cpu().numpy()
x1, y1, x2, y2 = map(int, [x1,y1,x2,y2])

# Build TOP crop box: shoulders -> hips (with padding)
if shoulders.size and hips.size:
    top_y1 = min(shoulders[:,1].min(), hips[:,1].min())
    top_y2 = hips[:,1].max()
    top_x1 = min(shoulders[:,0].min(), hips[:,0].min())
    top_x2 = max(shoulders[:,0].max(), hips[:,0].max())
else:
    top_x1, top_y1, top_x2, top_y2 = x1, y1, x2, int((y1+y2)/2)

# Build BOTTOM crop box: hips -> ankles (with padding)
if hips.size and ankles.size:
    bot_y1 = hips[:,1].min()
    bot_y2 = ankles[:,1].max()
    bot_x1 = min(hips[:,0].min(), ankles[:,0].min())
    bot_x2 = max(hips[:,0].max(), ankles[:,0].max())
else:
    bot_x1, bot_y1, bot_x2, bot_y2 = x1, int((y1+y2)/2), x2, y2

# padding
pad_x = int(0.10 * (x2 - x1))
pad_y = int(0.08 * (y2 - y1))

top_x1 = clamp(top_x1 - pad_x, 0, W-1)
top_x2 = clamp(top_x2 + pad_x, 0, W-1)
top_y1 = clamp(top_y1 - pad_y, 0, H-1)
top_y2 = clamp(top_y2 + pad_y, 0, H-1)

bot_x1 = clamp(bot_x1 - pad_x, 0, W-1)
bot_x2 = clamp(bot_x2 + pad_x, 0, W-1)
bot_y1 = clamp(bot_y1 - pad_y, 0, H-1)
bot_y2 = clamp(bot_y2 + pad_y, 0, H-1)

top_crop = img_bgr[top_y1:top_y2, top_x1:top_x2].copy()
bot_crop = img_bgr[bot_y1:bot_y2, bot_x1:bot_x2].copy()

top_crop_path = "/content/top_crop.jpg"
bot_crop_path = "/content/bottom_crop.jpg"
cv2.imwrite(top_crop_path, top_crop)
cv2.imwrite(bot_crop_path, bot_crop)

# visualize boxes
vis = img_bgr.copy()
cv2.rectangle(vis, (top_x1, top_y1), (top_x2, top_y2), (0,255,0), 3)
cv2.rectangle(vis, (bot_x1, bot_y1), (bot_x2, bot_y2), (255,0,0), 3)

plt.figure(figsize=(7,7))
plt.imshow(cv2.cvtColor(vis, cv2.COLOR_BGR2RGB))
plt.axis("off")
plt.title("Green=TOP crop, Blue=BOTTOM crop")
plt.show()

# show the crops
plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.imshow(cv2.cvtColor(top_crop, cv2.COLOR_BGR2RGB))
plt.axis("off")
plt.title("TOP crop")

plt.subplot(1,2,2)
plt.imshow(cv2.cvtColor(bot_crop, cv2.COLOR_BGR2RGB))
plt.axis("off")
plt.title("BOTTOM crop")
plt.show()

top_crop_path, bot_crop_path

from PIL import Image
import matplotlib.pyplot as plt

top_crop_path = "/content/top_crop.jpg"
bottom_crop_path = "/content/bottom_crop.jpg"

plt.figure(figsize=(10,4))
plt.subplot(1,2,1)
plt.imshow(Image.open(top_crop_path).convert("RGB"))
plt.axis("off")
plt.title("TOP crop")

plt.subplot(1,2,2)
plt.imshow(Image.open(bottom_crop_path).convert("RGB"))
plt.axis("off")
plt.title("BOTTOM crop")
plt.show()

person_path = person_path  # from your upload cell

try:
    skin_from_body = estimate_skin_profile_detailed(person_path, show=True)
    skin_used = skin_from_body
    print("Using skin tone from full-body photo:", skin_used["skin_description"])
except Exception as e:
    skin_used = skin_profile_detailed  # from your earlier face image
    print("Could not estimate skin from full-body photo, using previous face profile.")
    print("Reason:", str(e))
    print("Using:", skin_used["skin_description"])

occasion_text = "office meeting"   # change to: "wedding", "college party", "interview", etc.

recs_person = recommend_bottoms_personalized(
    top_img_path=top_crop_path,
    occasion_text=occasion_text,
    skin_profile=skin_used,
    k=5,
    search_k=150
)

recs_person[["label","img_score","txt_score","harmony_score","skin_score","final_personal"]]

show_outfit_2piece(
    top_crop_path,
    recs_person.rename(columns={"final_personal":"score"}),
    title=f"From PERSON TOP crop → Recommended bottoms | occasion='{occasion_text}' | {skin_used['skin_description']}"
)

import numpy as np, faiss, pandas as pd

meta = pd.read_csv("/content/fashion_reco_index/meta.csv")
emb_all = np.load("/content/fashion_reco_index/clip_emb.npy")

TOP_CLASSES = {"casual_shirts", "formal_shirts", "printed_tshirts", "solid_tshirts", "printed_hoodies"}

tops_meta_idx = meta.index[meta["label"].isin(TOP_CLASSES)].to_numpy()
emb_tops = emb_all[tops_meta_idx].astype("float32")

D = emb_tops.shape[1]
index_tops = faiss.IndexFlatIP(D)
index_tops.add(emb_tops)

print("Top index size:", index_tops.ntotal)

import numpy as np

def recommend_tops_free_text(bottom_img_path, occasion_text, k=5, search_k=120, w_img=0.70, w_txt=0.30):
    occasion_text = (occasion_text or "").strip()
    if len(occasion_text) == 0:
        occasion_text = "casual everyday"

    # 1) retrieve candidate tops by image similarity
    q_img = clip_embed_one(bottom_img_path)
    img_scores, idxs = index_tops.search(q_img, search_k)

    picked_meta_rows = tops_meta_idx[idxs[0]]
    cand = meta.iloc[picked_meta_rows].copy()
    cand["img_score"] = img_scores[0]

    # 2) text score using templates (tops-focused)
    templates = [
        f"men's {occasion_text} shirt",
        f"men's {occasion_text} t-shirt",
        f"men's {occasion_text} hoodie",
    ]
    t = np.mean([clip_text_embed_one(t) for t in templates], axis=0)  # (1,512)
    t = t / np.linalg.norm(t, axis=1, keepdims=True)

    cand_emb = emb_all[picked_meta_rows]
    cand["txt_score"] = (cand_emb @ t.T).reshape(-1)

    # 3) combine
    cand["final_score"] = w_img*cand["img_score"] + w_txt*cand["txt_score"]
    cand = cand.sort_values("final_score", ascending=False).head(k).reset_index(drop=True)
    return cand[["path","label","img_score","txt_score","final_score"]]

def recommend_tops_personalized(bottom_img_path, occasion_text, skin_profile, k=5, search_k=150,
                               w_clip=0.60, w_harmony=0.20, w_skin=0.20):
    cand = recommend_tops_free_text(bottom_img_path, occasion_text, k=max(k, 10), search_k=search_k).copy()

    # color stats
    cand["top_hsv"] = cand["path"].apply(clothing_color_stats)
    bottom_hsv = clothing_color_stats(bottom_img_path)

    # harmony: treat candidate top as "top" and query as "bottom"
    cand["harmony_score"] = cand["top_hsv"].apply(lambda top_hsv: color_harmony_score(top_hsv, bottom_hsv))

    # skin match for candidate top
    undertone = skin_profile["undertone"]
    cand["skin_score"] = cand["top_hsv"].apply(lambda st: skin_match_score(st, undertone))

    cand["final_personal"] = (
        w_clip * cand["final_score"] +
        w_harmony * cand["harmony_score"] +
        w_skin * cand["skin_score"]
    )

    cand = cand.sort_values("final_personal", ascending=False).head(k).reset_index(drop=True)
    return cand

bottom_crop_path = "/content/bottom_crop.jpg"
occasion_text = "office meeting"  # user can type anything

recs_top = recommend_tops_personalized(
    bottom_img_path=bottom_crop_path,
    occasion_text=occasion_text,
    skin_profile=skin_used,   # from Step 14.4
    k=5
)

recs_top[["label","img_score","txt_score","harmony_score","skin_score","final_personal"]]

show_outfit_2piece(
    bottom_crop_path,
    recs_top.rename(columns={"final_personal":"score"}),
    title=f"From PERSON BOTTOM crop → Recommended tops | occasion='{occasion_text}' | {skin_used['skin_description']}"
)

import numpy as np

CLOTHING_PROMPTS = [
    "a photo of clothing",
    "a photo of a shirt",
    "a photo of pants",
    "a photo of a t-shirt",
    "a photo of a hoodie",
    "a fashion product photo",
]
NONCLOTHING_PROMPTS = [
    "a photo of a car",
    "a photo of a dog",
    "a photo of food",
    "a photo of a building",
    "a photo of nature landscape",
    "a random object photo",
]

def mean_text_vec(prompts):
    vecs = np.vstack([clip_text_embed_one(p) for p in prompts])  # (n,512)
    v = vecs.mean(axis=0, keepdims=True)
    v = v / np.linalg.norm(v, axis=1, keepdims=True)
    return v.astype("float32")

cloth_vec = mean_text_vec(CLOTHING_PROMPTS)
non_vec   = mean_text_vec(NONCLOTHING_PROMPTS)

def is_clothing_image(img_path, margin=0.03):
    v = clip_embed_one(img_path)  # (1,512) normalized
    cloth_score = float(v @ cloth_vec.T)
    non_score   = float(v @ non_vec.T)
    ok = cloth_score > (non_score + margin)
    return ok, cloth_score, non_score

ok, cs, ns = is_clothing_image("/content/mens-shirts.jpg")
print("is_clothing:", ok, "| clothing_score:", cs, "| non_clothing_score:", ns)

def confident_prediction(pred_dict, min_conf=0.70):
    return pred_dict["conf"] >= min_conf

def enforce_similarity_threshold(recs_df, min_score=0.22):
    # scores are cosine similarities; tune min_score based on observation
    if len(recs_df) == 0:
        return recs_df, False
    strong = float(recs_df.iloc[0]["score"]) >= min_score
    return recs_df, strong

import numpy as np

CLOTHING_PROMPTS = [
    "a photo of clothing",
    "a photo of a shirt",
    "a photo of pants",
    "a photo of a t-shirt",
    "a photo of a hoodie",
    "a fashion product photo",
]
NONCLOTHING_PROMPTS = [
    "a photo of a car",
    "a photo of a dog",
    "a photo of food",
    "a photo of a building",
    "a photo of nature landscape",
    "a random object photo",
]

def _mean_text_vec(prompts):
    vecs = np.vstack([clip_text_embed_one(p) for p in prompts])  # (n,512)
    v = vecs.mean(axis=0, keepdims=True)
    v = v / np.linalg.norm(v, axis=1, keepdims=True)
    return v.astype("float32")

cloth_vec = _mean_text_vec(CLOTHING_PROMPTS)
non_vec   = _mean_text_vec(NONCLOTHING_PROMPTS)

def is_clothing_image(img_path, margin=0.03):
    """
    Returns (ok, clothing_score, nonclothing_score).
    If ok=False => ask user to upload a clothing/person image.
    """
    v = clip_embed_one(img_path)  # normalized (1,512)
    clothing_score = float(v @ cloth_vec.T)
    non_score      = float(v @ non_vec.T)
    ok = clothing_score > (non_score + margin)
    return ok, clothing_score, non_score

def safe_demo(img_path, occasion_text="casual everyday", skin_profile=None,
              classifier_choice="ensemble",
              min_class_conf=0.70,
              min_match_img_score=0.22,
              reco_k=5):
    # 1) OOD check
    ok, cs, ns = is_clothing_image(img_path)
    if not ok:
        print(f"Input rejected: does not look like clothing/person.")
        print(f"CLIP clothing_score={cs:.3f} nonclothing_score={ns:.3f}")
        print("Please upload a clear clothing item image or full-body person image.")
        return None, None

    # 2) Classify (both + ensemble)
    r, e, ens = classify_both(img_path)
    chosen = {"resnet": r, "effnet": e, "ensemble": ens}[classifier_choice]

    print("ResNet18 :", r["pred_label"], "| conf:", round(r["conf"], 4))
    print("EffNet-B0:", e["pred_label"], "| conf:", round(e["conf"], 4))
    print("Ensemble :", ens["pred_label"], "| conf:", round(ens["conf"], 4))
    print("Chosen   :", chosen["pred_label"], "| conf:", round(chosen["conf"], 4))

    # 3) Confidence check
    if chosen["conf"] < min_class_conf:
        print(f"Low confidence (<{min_class_conf}). Please upload a clearer image or allow manual label selection.")
        return chosen, None

    if skin_profile is None:
        # default: no skin personalization
        skin_profile = {"undertone": "neutral"}

    pred_label = chosen["pred_label"]

    # 4) Recommend
    if pred_label in TOP_CLASSES:
        recs = recommend_bottoms_personalized(img_path, occasion_text, skin_profile, k=reco_k, search_k=150)

        # similarity quality check using img_score (pure CLIP image-image)
        if len(recs) == 0 or float(recs["img_score"].max()) < min_match_img_score:
            print(f"No strong bottom match found (max img_score < {min_match_img_score}).")
            print("Try another photo or expand the catalog/wardrobe.")
            return chosen, recs

        show_outfit_2piece(
            img_path,
            recs.rename(columns={"final_personal":"score"}),
            title=f"TOP → Bottoms | occasion='{occasion_text}' | undertone={skin_profile.get('undertone','?')}"
        )
        return chosen, recs

    elif pred_label in BOTTOM_CLASSES:
        recs = recommend_tops_personalized(img_path, occasion_text, skin_profile, k=reco_k, search_k=150)

        if len(recs) == 0 or float(recs["img_score"].max()) < min_match_img_score:
            print(f"No strong top match found (max img_score < {min_match_img_score}).")
            print("Try another photo or expand the catalog/wardrobe.")
            return chosen, recs

        show_outfit_2piece(
            img_path,
            recs.rename(columns={"final_personal":"score"}),
            title=f"BOTTOM → Tops | occasion='{occasion_text}' | undertone={skin_profile.get('undertone','?')}"
        )
        return chosen, recs

    else:
        print("Predicted class not mapped to top/bottom. Showing similar items only.")
        recs = recommend_similar_all(img_path, top_k=reco_k)  # if you still have it
        return chosen, recs

chosen, recs = safe_demo(
    "/content/mens-shirts.jpg",
    occasion_text="office meeting",
    skin_profile=skin_profile_detailed,
    classifier_choice="ensemble"
)

def style_from_person_photo(person_path, occasion_text="casual everyday", use_skin=True, k=5):
    # 1) Pose crop (TOP/BOTTOM)
    import cv2, numpy as np
    from ultralytics import YOLO

    # load pose model once (cache it)
    global pose_model
    if "pose_model" not in globals() or pose_model is None:
        pose_model = YOLO("yolov8n-pose.pt")

    img_bgr = cv2.imread(person_path)
    if img_bgr is None:
        raise ValueError("Could not read person image path.")

    H, W = img_bgr.shape[:2]
    res = pose_model.predict(person_path, conf=0.25, verbose=False)[0]
    if res.keypoints is None or len(res.keypoints) == 0:
        raise ValueError("No person keypoints detected. Upload a clearer full-body standing photo.")

    boxes_conf = res.boxes.conf.cpu().numpy()
    best_i = int(np.argmax(boxes_conf))
    kpts = res.keypoints.xy[best_i].cpu().numpy()

    # COCO indices
    L_SH, R_SH = 5, 6
    L_HIP, R_HIP = 11, 12
    L_ANK, R_ANK = 15, 16

    def clamp(v, lo, hi):
        return int(max(lo, min(hi, v)))

    def safe_xy(points):
        pts = points.copy()
        good = ~np.isnan(pts[:,0]) & ~np.isnan(pts[:,1]) & (pts[:,0] > 1) & (pts[:,1] > 1)
        return pts[good] if good.any() else pts

    shoulders = safe_xy(kpts[[L_SH, R_SH]])
    hips      = safe_xy(kpts[[L_HIP, R_HIP]])
    ankles    = safe_xy(kpts[[L_ANK, R_ANK]])

    x1, y1, x2, y2 = res.boxes.xyxy[best_i].cpu().numpy()
    x1, y1, x2, y2 = map(int, [x1,y1,x2,y2])

    if shoulders.size and hips.size:
        top_y1 = min(shoulders[:,1].min(), hips[:,1].min())
        top_y2 = hips[:,1].max()
        top_x1 = min(shoulders[:,0].min(), hips[:,0].min())
        top_x2 = max(shoulders[:,0].max(), hips[:,0].max())
    else:
        top_x1, top_y1, top_x2, top_y2 = x1, y1, x2, int((y1+y2)/2)

    if hips.size and ankles.size:
        bot_y1 = hips[:,1].min()
        bot_y2 = ankles[:,1].max()
        bot_x1 = min(hips[:,0].min(), ankles[:,0].min())
        bot_x2 = max(hips[:,0].max(), ankles[:,0].max())
    else:
        bot_x1, bot_y1, bot_x2, bot_y2 = x1, int((y1+y2)/2), x2, y2

    pad_x = int(0.10 * (x2 - x1))
    pad_y = int(0.08 * (y2 - y1))

    top_x1 = clamp(top_x1 - pad_x, 0, W-1); top_x2 = clamp(top_x2 + pad_x, 0, W-1)
    top_y1 = clamp(top_y1 - pad_y, 0, H-1); top_y2 = clamp(top_y2 + pad_y, 0, H-1)

    bot_x1 = clamp(bot_x1 - pad_x, 0, W-1); bot_x2 = clamp(bot_x2 + pad_x, 0, W-1)
    bot_y1 = clamp(bot_y1 - pad_y, 0, H-1); bot_y2 = clamp(bot_y2 + pad_y, 0, H-1)

    top_crop = img_bgr[top_y1:top_y2, top_x1:top_x2].copy()
    bot_crop = img_bgr[bot_y1:bot_y2, bot_x1:bot_x2].copy()

    top_crop_path = "/content/top_crop.jpg"
    bot_crop_path = "/content/bottom_crop.jpg"
    cv2.imwrite(top_crop_path, top_crop)
    cv2.imwrite(bot_crop_path, bot_crop)

    # 2) Skin profile (optional)
    skin_used = {"undertone": "neutral"}
    if use_skin:
        try:
            skin_used = estimate_skin_profile_detailed(person_path, show=False)
        except Exception:
            # fallback to whatever you already computed earlier if available
            if "skin_profile_detailed" in globals():
                skin_used = skin_profile_detailed

    print("Occasion:", occasion_text)
    print("Skin:", skin_used.get("skin_description", f"undertone={skin_used.get('undertone','?')}"))

    # 3) Recommend bottoms from TOP crop
    print("\n--- TOP crop → bottoms ---")
    safe_demo(top_crop_path, occasion_text=occasion_text, skin_profile=skin_used, classifier_choice="ensemble", reco_k=k)

    # 4) Recommend tops from BOTTOM crop
    print("\n--- BOTTOM crop → tops ---")
    safe_demo(bot_crop_path, occasion_text=occasion_text, skin_profile=skin_used, classifier_choice="ensemble", reco_k=k)

    return top_crop_path, bot_crop_path, skin_used

# person_path must be the uploaded full-body image path you used earlier
style_from_person_photo(person_path, occasion_text="office meeting", use_skin=True, k=5)

from google.colab import drive
drive.mount("/content/drive")

import os, shutil

DRIVE_DIR = "/content/drive/MyDrive/PersonalFashionStylist"
os.makedirs(DRIVE_DIR, exist_ok=True)

for sub in ["models", "clip_index", "notebook_outputs"]:
    os.makedirs(os.path.join(DRIVE_DIR, sub), exist_ok=True)

DRIVE_DIR

!cp /content/resnet18_best.pt "{DRIVE_DIR}/models/"
!cp /content/effb0_best.pt "{DRIVE_DIR}/models/"
!cp /content/cnn_best.pt "{DRIVE_DIR}/models/"

!ls -lh "{DRIVE_DIR}/models"

!cp -r /content/fashion_reco_index "{DRIVE_DIR}/clip_index/"

!find "{DRIVE_DIR}/clip_index/fashion_reco_index" -maxdepth 1 -type f -print

